### ISSUE TITLE
Unique Usernames

### ISSUE THREAD

**Issue by ryanhlewis** [appwrite/appwrite#1014]
## 🚀 Feature

As simple as the title, preferably, there would be some option within all the Login Methods and various OAuth Providers to enable "Unique Usernames", which simply checks if usernames already exist in the database. It's just a simple boolean.

## Have you spent some time to check if this issue has been raised before?

Yup! All queries in Issues and Discussions never breach this topic.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes.

## Pitch

Nowadays, unique usernames are used everywhere from Instagram, to Facebook, to Xbox, to Twitter - you name it.
As AppWrite functions as a database for similar apps, this is surely a feature that can be easily implemented and will save a lot of trouble on the part of the programmer not having to result to a strange workaround like a custom database table of usernames to check against.

This feature would be implemented in https://github.com/appwrite/appwrite/blob/master/app/controllers/api/account.php at Line 78-88. It would be an IF statement. I have taken the excerpt and pseudocoded into it below.

```
$profile = $projectDB->getCollectionFirst([ // Get user by email address
            'limit' => 1,
            'filters' => [
                '$collection='.Database::SYSTEM_COLLECTION_USERS,
                'email='.$email,
            ],
        ]);

//Pseudocode for a unique username check.      I'm not exactly sure how your DB is set up, so this is largely guessing.
if(uniqueUsernameVerify) {

$profile = $projectDB->getCollectionFirst([ // Get user by email address AND name
            'limit' => 1,
            'filters' => [
                '$collection='.Database::SYSTEM_COLLECTION_USERS,
                'email='.$email,
                'name='.$name,
            ],
        ]);

}

        if (!empty($profile)) {
            throw new Exception('Account already exists', 409);
        }

```

**Comment by eldadfux** [comment]
@ryanhlewis sorry for the late response, how would you view the API signature change with this feature?

We would probably need to expose a new method to update the username, would you see any other changes to different endpoints?

Open questions:
- Should this effect our OAuth integration?
- Should we try and fetch usernames from OAuth providers when this is the authentication method that is being used?
- What happens if an OAuth user is already exists? (considering we did try to fetch it)

**Comment by ryanhlewis** [comment]
It shouldn't affect much. It's a feature request. 

If anything, you should have already been grabbing usernames and names of OAuth accounts and placing them inside the database. What the hell do you call them in your applications? EFWFEWF@gmail.com, Welcome to the Appwrite-Enabled app! It's ridiculous if you haven't already accounted for grabbing usernames or at least creating them from OAuth.

1. Yes. You really should have already accounted for this, realistically.
2. Yes. See above.
3. Grab me another number, buckaroo. "kangarooman" is taken? "kangarooman1"? Fine.

**Comment by canbrkkyGit** [comment]
@TorstenDittmann 

What if an app provides opportunity to create accounts with OAuth2 providers, The problem is that , account.createOAuth2Session doesn't take userId argument as account.create does, it generate its userId automatically.  

wish it could take the **userId** argument , 

For example, as a flutter user, Firstly, i would have requested a username input from user and then navigate the user to webview provided by account.createOAuth2Session(userId : "sampleUsername").
