### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by Asored-D** [appwrite/appwrite#1074]
## 🚀 Feature

Hi appwrite team,

I plan to switch from Firebase (Auth, Database and Cloud Functions) completely to Appwrite. I already could implement authentication in production and it works really great. I really appreciate your good work!

The next step would be the database migration. While searching all issue topics, I found the following: 
https://github.com/appwrite/appwrite/issues/909

MongoDB is a known database and I really like to work with. So I have the decision to

1) Wait until MongoDB is released from your side
2) or migrating with the current appwrite database system. But later, when MongoDB was released, I have to migrate again

So my question is: Do you plan to integrate MongoDB? If yes, what do you think when this feature will be released? So i would wait with migrating until. Otherwise, if you don't plan to include this feature, I could start the work with the current database.

Many thanks in advance for your response!

## Have you spent some time to check if this issue has been raised before?

Yes. I found this reference: https://github.com/appwrite/appwrite/issues/909

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes

## Pitch

I think MongoDB is a known and very good database which many users like to work with. Would be an +999999 feature :-)

**Comment by TorstenDittmann** [comment]
Grüße @Asored-D 👋🏻 

We are actually working right now on refactoring our database solution, a RFC can be found here: https://github.com/appwrite/rfc/pull/21

We are also trying to support MongoDB as a Database solution with that, but it might not be the way you would expect it. 

Appwrite's current database solution offers a lot of features (Validation, Abuse Control, etc), that we couldn't integrate so easily across many database solutions and letting the developers communicate directly with it. Meaning the Appwrite Database will always provide the same interface to any database used in the back (Presumably, because the planning for this is still in an early/mid phase and can change constantly).

Reason for this approach is to offer the same developer experience overall and not limiting the developer by the database used in the back (More freedom in in choosing a managed provider and seamless migrations to a different one).

I hope I could answer your question and if you have any more, feel free to ask us here 👍🏻

**Comment by ArpanKIIT2017** [comment]
Is there any update on this?

**Comment by lubna-07** [comment]
@Asored-D  Is there any update? What method did you follow to migrate the database?
