### ISSUE TITLE
Connection timed out when trying to deploy to Digitalocean

### ISSUE THREAD

**Issue by MaddPenguin** [appwrite/appwrite#1098]
I'm trying to deploy Appwrite on my VPS (**Docker 19.03.12 on Ubuntu 20.04**). Somehow, this error pops up. 

> An HTTP request took too long to complete. Retry with --verbose to obtain debug information.'

Full error:

> root@project:~# docker run -it --rm \
>      --volume /var/run/docker.sock:/var/run/docker.sock \
>      --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \
>      --entrypoint="install" \
>      appwrite/appwrite:0.7.2 --verbose
> Starting Appwrite installation...
> Choose your server HTTP port: (default: 80)
> 
> Choose your server HTTPS port: (default: 443)
> 
> Choose a secret API key, make sure to make a backup of your key in a secure location (default: 'your-secret-key')
> 
> Enter your Appwrite hostname (default: 'localhost')
> 
> Enter a DNS A record hostname to serve as a CNAME for your custom domains.\nYou can use the same value as used for the Appwrite hostname. (default: 'localhost')
> 
> Running "docker-compose -f /usr/src/code/appwrite/docker-compose.yml up -d --remove-orphans --renew-anon-volumes"
> Failed to install Appwrite dockers
> Removing appwrite-schedule
> Removing appwrite-maintenance
> Removing appwrite-worker-certificates
> Removing appwrite-worker-webhooks
> Removing appwrite-worker-usage
> Recreating appwrite-telegraf ... done
> Recreating appwrite-influxdb ... done
> Recreating appwrite-clamav   ... done
> Recreating appwrite-mariadb  ... done
> Recreating appwrite-redis    ... done
> Recreating appwrite-worker-mails ... 
> Recreating appwrite-worker-tasks ... 
> Recreating appwrite-worker-functions ... 
> Recreating af7f82e3558e_appwrite-maintenance ... 
> Recreating appwrite-worker-audits            ... 
> Recreating 2d8ce035b81c_appwrite-worker-webhooks ... 
> Recreating ebceaa4ec171_appwrite-worker-certificates ... 
> Recreating appwrite-worker-deletes                   ... 
> Recreating 5d577957081d_appwrite-schedule            ... 
> Recreating f0b9cb3092c6_appwrite-worker-usage        ... 
> Recreating appwrite                                  ... 
> 
> ERROR: for 2d8ce035b81c_appwrite-worker-webhooks  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for 5d577957081d_appwrite-schedule  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for ebceaa4ec171_appwrite-worker-certificates  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for af7f82e3558e_appwrite-maintenance  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-worker-deletes  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-worker-audits  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-worker-tasks  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-worker-functions  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-worker-mails  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
> 
> ERROR: for f0b9cb3092c6_appwrite-worker-usage  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
> 
> ERROR: for appwrite-worker-tasks  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-worker-functions  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-maintenance  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-worker-deletes  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-worker-audits  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-schedule  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-worker-certificates  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-worker-mails  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
> 
> ERROR: for appwrite-worker-webhooks  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
> 
> ERROR: for appwrite-worker-usage  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
> An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
> If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

Appwrite has no issue running locally on my machine. The error only occurs when deploying to DO.

I've tried disabling the firewall on my VPS, but it did nothing.

**Comment by rodgav** [comment]
Failed to install Appwrite dockers
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating network "appwrite_appwrite" with the default driver
Creating network "appwrite_gateway" with the default driver
Creating volume "appwrite_appwrite-mariadb" with default driver
Creating volume "appwrite_appwrite-redis" with default driver
Creating volume "appwrite_appwrite-cache" with default driver
Creating volume "appwrite_appwrite-uploads" with default driver
Creating volume "appwrite_appwrite-certificates" with default driver
Creating volume "appwrite_appwrite-functions" with default driver
Creating volume "appwrite_appwrite-influxdb" with default driver
Creating volume "appwrite_appwrite-config" with default driver
Pulling mariadb (appwrite/mariadb:1.2.0)...
Pulling redis (redis:6.0-alpine3.12)...
Pulling influxdb (appwrite/influxdb:1.0.0)...
Pulling traefik (traefik:2.5)...
Pulling telegraf (appwrite/telegraf:1.2.0)...
Creating appwrite-influxdb ...
Creating appwrite-mariadb  ...
Creating appwrite-telegraf ...
Creating appwrite-redis    ...
Creating appwrite-mariadb  ... done
Creating appwrite-influxdb ... done
Creating appwrite-telegraf ... done
Creating appwrite-redis    ... done
Creating appwrite-worker-certificates ...
Creating appwrite-realtime            ...
Creating appwrite-maintenance         ...
Creating appwrite-schedule            ...
Creating appwrite-worker-usage        ...
Creating appwrite-worker-audits       ...
Creating appwrite-worker-webhooks     ...
Creating appwrite-worker-tasks        ...
Creating appwrite-worker-functions    ...
Creating appwrite-worker-deletes      ...
Creating appwrite                     ...
Creating appwrite-worker-mails        ...
Creating appwrite-realtime            ... done

ERROR: for appwrite-worker-certificates  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-audits  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-usage  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-functions  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-schedule  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-maintenance  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-webhooks  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-tasks  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-deletes  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-mails  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-certificates  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-audits  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-usage  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-functions  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-schedule  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-maintenance  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-webhooks  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-tasks  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-deletes  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite-worker-mails  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appwrite  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal


Docker version 20.10.8, build 3967b7d

**Comment by damywise** [comment]
I had this problem as well but I found a way to fix it:
_Execute the command again a few times_
Usually around 3-5 times. Maybe more.
