### ISSUE TITLE
i m using linux ubuntu

### ISSUE THREAD

**Issue by imronpuji** [appwrite/appwrite#12]
i cant install,, and icant use can you help me please

**Comment by eldadfux** [comment]
@imronpuji Any error message? In order to help we must have more details.

**Comment by imronpuji** [comment]
I dont see,,, how to install it on linux terminal,,, i dont know how to open locale host after it installed...

**Comment by imronpuji** [comment]
Sorry because im new,,, using linux ubuntu,,, i didnt see how to use it... Can you helpme please,, i didnt find error message because i didnt install it...

**Comment by eldadfux** [comment]
@imronpuji installing Appwrite for linux is same as on mac. If you are trying to install it on a server instead of your localhost use your server ip to access the console.

If you still struggle I would suggests reading a little more about how Docker works. 

I guess this not a specific Appwrite issue so I am closing the issue. For any more help you can also use the 'Appwrite Developers' group on Facebook.
