### ISSUE TITLE
Error when using auth session

### ISSUE THREAD

**Issue by cambo2015** [appwrite/appwrite#1203]
I received an "Unhandled Rejection (AppwriteException): User (role: guest) missing scope (account)" error when trying to removea user session (log out). Thanks

I am using React 17.0.2

**Comment by designlook** [comment]
Yes I also got this error when trying to do a Google login.

code: 401
message: "User (role: guest) missing scope (account)"
version: "0.8.0"

**Comment by eldadfux** [comment]
`User (role: guest) missing scope (account)` - means the user session was not detected by Appwrite. Appwrite uses a secure cookie and localstorage fallback for storing the session key. Some browsers like Firefox and Safari don't respect 3rd party cookies for privacy reasons - which forces you to make sure your Appwrite API and web application are using the same top level domain. For example:

Appwrite -> `appwrite.mydomain.com`
Website -> `mydomain.com` or `myapp.mydomain.com`

Currently Appwrite can't set the localstorage fallback on OAuth logins. Using the same top level domain is the most secure way to handle user sessions. You can set a domain by pointing it to your Appwrite instance, or by using the custom domains feature in the Appwrite console (project -> settings -> custom domains).

More info on custom domains in Appwrite and 3rd party cookies available here: 
https://appwrite.io/docs/custom-domains

**Comment by designlook** [comment]
Thanks @eldadfux ! Finally understand the error. Wish message was clearer. 

How could I test it if I am running my app on localhost but the appwite is on my server on site with domain name? I configure Google Oauth to accept localhost and in my react app I set appetite to point to my domain. But it still gives me that error when logging in. Although doing queries on the database returns results. Just can't log in.

**Comment by cambo2015** [comment]
@eldadfux Thanks that makes sense. If this happens for others this is was the mistake:  I forgot to put async/await for the get user function. As soon as I did the error went away.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by designlook** [comment]
I guess for what I am trying to do, it's not yet supported by appwrite. I am trying to use one domain as database using appwrite. And other domains point to it for db needs. Similar to what I do with firebase right now.

**Comment by eldadfux** [comment]
> I guess for what I am trying to do, it's not yet supported by appwrite. I am trying to use one domain as database using appwrite. And other domains point to it for db needs. Similar to what I do with firebase right now.

If you can give more info about your use case we might have a better idea if Appwrite is able or will able to support this use case.

**Comment by designlook** [comment]
Thanks @eldadfux . I would use it like Firebase. So if I had a dedicated several with multiple domains, I would use one for Appwrite to act like Firebase. And in my other domains, would all use that domain to host my data. Right now, I cannot seem to get Appwrite to work if the top level domain is different than Appwrite domain when I use Google or Facebook OAuth with Appwrite.

**Comment by TorstenDittmann** [comment]
Gonna close this issue, since the initial question got answered.

**Comment by dominickolbe** [comment]
@designlook regarding your issue with `localhost`. I'm using brave and you can enable third party cookie access for localhost. Hope that helps you

**Comment by iamyxsh** [comment]
> > I guess for what I am trying to do, it's not yet supported by appwrite. I am trying to use one domain as database using appwrite. And other domains point to it for db needs. Similar to what I do with firebase right now.
> 
> If you can give more info about your use case we might have a better idea if Appwrite is able or will able to support this use case.

Mate, I am using appwrite for backend (Go) and frontend (React + Flutter). I am providing the correct headers - "X-Appwrite-Project" and "X-Appwrite-key" but still if I want to do anything with the "account" api (getting the account info by passing Bearer Token in Auth header), it is showing me this error - app.(random-string)@service.(my-domain) (role: application) missing scope (account)". Any idea why? Thanks. :)

**Comment by eldadfux** [comment]
> > > I guess for what I am trying to do, it's not yet supported by appwrite. I am trying to use one domain as database using appwrite. And other domains point to it for db needs. Similar to what I do with firebase right now.
> > 
> > 
> > If you can give more info about your use case we might have a better idea if Appwrite is able or will able to support this use case.
> 
> Mate, I am using appwrite for backend (Go) and frontend (React + Flutter). I am providing the correct headers - "X-Appwrite-Project" and "X-Appwrite-key" but still if I want to do anything with the "account" api (getting the account info by passing Bearer Token in Auth header), it is showing me this error - app.(random-string)@service.(my-domain) (role: application) missing scope (account)". Any idea why? Thanks. :)

The API key has no access to the account API because it's running as an application and not a user, so there is no account to show. To access the account API from a server side, you need the client SDK to generate a JWT that you can pass to your server and perform actions on behalf of a specific user.

**Comment by koodeau** [comment]
> 

I think this issue should be reopened or referenced in a new one

**Comment by koodeau** [comment]
> > > I guess for what I am trying to do, it's not yet supported by appwrite. I am trying to use one domain as database using appwrite. And other domains point to it for db needs. Similar to what I do with firebase right now.
> > 
> > 
> > If you can give more info about your use case we might have a better idea if Appwrite is able or will able to support this use case.
> 
> Mate, I am using appwrite for backend (Go) and frontend (React + Flutter). I am providing the correct headers - "X-Appwrite-Project" and "X-Appwrite-key" but still if I want to do anything with the "account" api (getting the account info by passing Bearer Token in Auth header), it is showing me this error - app.(random-string)@service.(my-domain) (role: application) missing scope (account)". Any idea why? Thanks. :)

I think this issue should be reopened or referenced in a new one

**Comment by koodeau** [comment]
> Thanks @eldadfux ! Finally understand the error. Wish message was clearer.
> 
> How could I test it if I am running my app on localhost but the appwite is on my server on site with domain name? I configure Google Oauth to accept localhost and in my react app I set app to point to my domain to v1 account link. But it gives me that error when logging in. Although doing queries on the database returns results. Just can't log in.
> 
> The weird thing is I swear it was working before when I first installed appwrite. I just don't know what changed.

I think this issue should be reopened or referenced in a new one

**Comment by benjaminSchilling33** [comment]
I would like to create automated tests for my functions. For this purpose I first considered using the dart server SDK.
But as I learned from this thread, I will have to use the flutter client SDK instead, since the server SDK does not allow me to create a user session, which I need to allow my function to get its internal JWT for authenticating against the Appwrite API to create documents/store files which i have to do in the function.

What is the recommended way to solve this problem?

**Comment by greendesertsnow** [comment]
So will setting your CNAME config like this solve the issue for Appwrite and webhosting being in separate IP's?
![image](https://user-images.githubusercontent.com/88274580/207616937-cf73302e-ccc1-4123-ba6d-5c78675e81d6.png)

**Comment by robododge** [comment]
Hi I wanted to share my recent success at working through this with Appwrite and Next.js using OAuth with the google provider.  I think the majority of the questions here are in the context of developing locally, not production deployments.

Yes, you do need to set the appwrite domain name to something that is a subdomain of where your webapp is running.
I have an unused dnsname that I use to play with in these cases  "stevecoin.io".  For local development,  If you don't have a dns name, you can fbi.com because *.fbi.com always resolves to 127.0.0.1.  You may be able to do this with a local DNS server or even /etc/hosts, but I didn't try those. You can use my stevecoin.io for now, unless I end up changing it. :). 

1. Set in the appwrite .env file - _APP_DOMAIN=appwrite.stevecoin.io, _APP_DOMAIN_TARGET=stevecoin.io,  this will allow app-write to generate a self-signed cert appwrite.stevecoin.io
2. Make sure appwrite is listening on the standard ports 80 and 443 in the traefik load balancer, I controlled this directly in docker-compose.yaml `    ports:
      - 80:80
      - 443:443`
3. Fully stop and reload the appwrite docker compose:  `docker compose stop` and `docker compose  up -d --remove-orphans`
4. Ensure that appwrite is deployed with the correct environment variables: `docker compose exec appwrite vars | grep DOM`, should see the values for stevecoin.io above
5. In the next.js app, I made sure to call the https:// endpoint of appwrite in my appwright SDK like so ` appwrite.setEndpoint("https://appwrite.stevecoin.io/v1").setProject("64318376edd95b3dbdac");`
6. When you start your next.js app, make sure it is listening on the root domain name, in my case start next.js with `"dev": "next dev -H stevecoin.io"` and access the app locally with http://stevecoint.io:3000.
7. You will need to navigate to https://appwrite.stevecoin.io in your local browser and then accept the suspicious self-signed certificate which was self signed by CN = TRAEFIK DEFAULT CERT
8. I proceeded with calling the appwrite API for OAuth flow with 'google' as my provider according the [docs for OAut2 sessions](https://appwrite.io/docs/client/account?sdk=web-default#accountCreateOAuth2Session).  _NOTE_ in Next.js you need to make sure you are in a client side component for this.
9. After you have completed an OAuth login, the secure http cookie with your appwrite session ID will stored in the appwrite server and only accessible if all communication was done using the https:// connection to the appwrite API endpoint.
10. Now, later when you want to [retrieve the current user session](https://appwrite.io/docs/client/account?sdk=web-default#accountGetSession) or the [current user account](https://appwrite.io/docs/client/account?sdk=web-default#accountGet), the appwrite sdk running in the client side next.js component will successfully retrieve it.
11. You can populate a session variable on the client side that will dictate if the user is logged in or not, for my case I place the account object into a React provider and expose it down the component tree.

**Comment by Khalilsqu** [comment]
I get the same error if there is no session using `account.getSession("current");`

I just want to know if the user has already logged in using `account.createOAuth2Session("google", xxx, xxx, [xxx, xxx])`. 

if there is a user session the logged-in user is directed away from the login page, if not the user can continue with Google log-in. 

The error disappears when the login is successful!

**Comment by dtronic-au** [comment]
Had a similar issue with account.get() - as mentioned above by 


> I get the same error if there is no session using `account.getSession("current");`
> 
> I just want to know if the user has already logged in using `account.createOAuth2Session("google", xxx, xxx, [xxx, xxx])`.
> 
> if there is a user session the logged-in user is directed away from the login page, if not the user can continue with Google log-in.
> 
> The error disappears when the login is successful and the user tries to revisit the login page!
> 
> ```
> const getCurrentSession = () => {
>   const client = new Client();
> 
>   const account = new Account(client);
>   client
>     .setEndpoint(process.env.NEXT_PUBLIC_ENDPOINT) 
>     .setProject(process.env.NEXT_PUBLIC_PROJECT_ID);
> 
>   const currentSession = account.getSession("current");
>   currentSession.then(
>     function (response) {
>       console.log(response);
>       router.push("/");
>     },
>     function (error) {
>       console.log(error);
>     }
>   );
> };
> ```

Making the above async and await(ing) the response should remove the 'exception'

The following is what I use to check for current session, then route accordingly..

![image](https://user-images.githubusercontent.com/36444846/232452238-f46cbe05-a6f3-44c2-8e14-4cd33827c6bb.png)

**Comment by robododge** [comment]
Yes, I had to put the await call inside of a try/catch block as well.  Here is my typescript code

```
//called from Next.js/React in a top-level component,  I  use useSWR() to call this and return the account object.
// the account object will be empty if no previous google OAuth2 session had been established.
async function getUserAccount() {
    let acct:Models.Account<Models.Preferences> | null = {} as Models.Account<Models.Preferences>
    try {
        acct = await awapi.getUserAccount()
    } catch (error) {
        console.error("Error gettign current user account!", error)
    }
    console.log("Account -=-", acct)
    return acct
}```

Here is my appwrite api wrapper 'awapi'
```
import { Client as Appwrite, Databases, Account } from "appwrite";
interface ISdk {
    dbobj: Databases | null
    acctobj: Account
}

let awapi = {
    clientSdk: null as null | ISdk,
    clientSideProvider: ()=> {
        if (awapi.clientSdk) {
            return awapi.clientSdk
        }
        console.log("attaching to DB now!")
        let appwrite = new Appwrite();
        
        appwrite.setEndpoint("https://appwrite.stevecoin.io/v1").setProject("64318376edd95b3dbdac");
        awapi.clientSdk = {dbobj:null, acctobj:new Account(appwrite)}
        return awapi.clientSdk
    },
    deleteCurrentSession: () => {
        return awapi.clientSideProvider().acctobj.deleteSession("current");
    },
    createOauthGoogle: () => {
        return awapi.clientSideProvider().acctobj.createOAuth2Session("google","http://stevecoin.io:3000")
    },
    getCurrentSession: () => {
        return awapi.clientSideProvider().acctobj.getSession('current')
    },
    getUserAccount: () => {
        return awapi.clientSideProvider().acctobj.get()
    },
}

export default awapi
```

**Comment by abhijivani3001** [comment]
> I received an "Unhandled Rejection (AppwriteException): User (role: guest) missing scope (account)" error when trying to removea user session (log out). Thanks
> 
> I am using React 17.0.2

You should allow appwrite.io to save your data in device.

![image](https://github.com/appwrite/appwrite/assets/117305467/69a98bf5-b6ff-4db6-b2d7-9d767aa4112f)
