### ISSUE TITLE
Ability to optionally name function tags

### ISSUE THREAD

**Issue by alexweininger** [appwrite/appwrite#1222]
## 🚀 Feature

The ability to optionally give function tags a name.

## Pitch

It's really hard to differentiate between tags since they just have dateCreated and their ID. Allowing users to name them would make it much easier to decipher which tag is which version of the function code.

**Comment by eldadfux** [comment]
This might work well with upcoming custom IDs 🤩  @appwrite/core what do you think?

**Comment by lohanidamodar** [comment]
Personally I can't find much of use except for identification, @alexweininger as a developer, you could just decide the version based on the timestamp, for example oldest one `v1` then increment in order based on the timestamp order. Also, if we will get ability of adding custom IDs then this problem is easily solved.

**Comment by TorstenDittmann** [comment]
Custom ID's can cut complexity when running a production and staging environment. So, all for it 👍🏻

**Comment by PineappleIOnic** [comment]
I wouldn't mind taking this one on :slightly_smiling_face:

**Comment by eldadfux** [comment]
Closing since it seems like most suggestions are to use custom IDs which are now available.
