### ISSUE TITLE
Automatically activate first tag

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1264]
## 🚀 Feature

When you deploy a code (let's say using CLI), it created a new function tag. Now you need to enter administration and mark this tag as an active.

Sure, this system is awesome for updating, but if I upload the first tag for a newly created function, I think we can agree to be sure I actually want to deploy this one.

## Have you spent some time to check if this issue has been raised before?

Discord discussion lead me to believe this is not part of the Appwrite. It should be possible using events, but I believe most of the appwrite function users (80+%) mark their first tag as active.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes, I believe this does not go against any rules.

## Pitch

As explained above, I believe most of the users do this already but as an additional step to click "Activate". 

Example:
-I code locally, test functions offline.. I make a script to build everything (from typescript to javascript), separate it and make new tags for it in Appwrite. Out of my 50 functions, 20 didnt change, 1 has a bug fixed and 29 are new functions. I believe you can mark these 29 as active automatically.

**Comment by Meldiron** [comment]
Sure, sounds reasonable, corporations surly need this extra step to keep everything secure.

In my opinion, default should be automatic activation as default options should be more welcoming for developers new to Appwrite. Huge corporations should have developers experienced enough to know about this environment variable before using it in production.

**Comment by mlucas-NU** [comment]
I agree with the security concerns above if automatic activation is the default, but I think it would be very handy to be able to enable such a feature in some circumstances. Allowing server maintainers to control this behavior means security-minded teams can define a process for manual/programmatic function activation and low-risk scenarios like quick prototyping/hackathons can get the benefits of automatic activation.

When I started writing this comment, I thought it would be nice to have a configuration file that could define which functions are activated but I'm not so sure. Using a configuration file and version control provides benefits such as:
* the config file can activate functions as soon as they are added, but on a per-function basis
* function activations can go through a peer-reviewed process
* a history of activations/deactivations would effectively be logged (but not in the most appealing way)
* activation changes can be deployed to many instances if appwrite is horizontally scaled to many compute instances, though any manual changes in the UI would be lost once servers are redeployed.
Configuration files for cloud functions may be worth its own ticket rather than distracting from the conversation at hand since topics like best practices and horizontal scaling are probably longer-term considerations.

**Comment by Meldiron** [comment]
Great comment @mlucas-NU , I didn't even think about that. It surly is a great idea to implement this inside each function separately rather than enabling it on the whole server/project. This way a new function (or even old ones on a small project) can automatically pick up the latest tag as active, meanwhile the lead developer can review the code and mark the function as "finished", so it stops activating new tags automatically.

How can this be implemented, tho? I believe package manager could take care of that... I think Heroku uses package.json for NodeJS projects to know how to start the application and what it needs. Maaaabye if we had `package.json` (or alternative in other languages) and set specific value such as `"appwrite": { "automaticActivation": true }`, Appwrite could check this file on every tag and decide what to do with such an information.

**Comment by TorstenDittmann** [comment]
Would adding a new param to the `createTag` function to automatically active the tag?

Meaning you can decide to activate a Tag directly when creating it 🤔

**Comment by Meldiron** [comment]
Yeah, that should do, but wouldn't it be harder to implement? This way it has to be added into every SDK (server-side, CLI), into frontend application into manual tag creation, ...

**Comment by PineappleIOnic** [comment]
We automatically generate most of our SDK's, So it shouldn't be too much of a issue

**Comment by TorstenDittmann** [comment]
> Yeah, that should do, but wouldn't it be harder to implement? This way it has to be added into every SDK (server-side, CLI), into frontend application into manual tag creation, ...

This way, the developers will have the option to activate any tag they upload - unrelated to if it is the first one to the function 🙂

**Comment by mark-apn** [comment]
Added a bash script to my deploy script that does this automatically via the updateTag CLI command. Works fine until there is a more integrated way. 

```bash
#!/bin/bash

# Execute the following commands and save result in variable 'result'
RESULT="$(appwrite functions createTag \
            --functionId="11aa8af23b7b0fb732db" \
            --command="dart main.dart" \
            --code="server/functions/create_puzzle" | grep \$id)"

# Strip ID from result
ID=${RESULT/\$id : /}

# Activate the new tag 
appwrite functions updateTag \
    --functionId="11aa8af23b7b0fb732db" \
    --tag=$ID
``

**Comment by eldadfux** [comment]
> > Yeah, that should do, but wouldn't it be harder to implement? This way it has to be added into every SDK (server-side, CLI), into frontend application into manual tag creation, ...
> 
> This way, the developers will have the option to activate any tag they upload - unrelated to if it is the first one to the function 🙂

I think this is the best solution, power to developers - let them make the calls while Appwrite try to provide sensible security minded and dev-friendly defaults as much as possible.

I think the implementation should be pretty easy. @Meldiron, now that you're part of @appwrite/core, would you like to pick it up? 😅
