### ISSUE TITLE
Dart: Account.createOAuth2Session should return the created sessions

### ISSUE THREAD

**Issue by JulianBissekkou** [appwrite/appwrite#1433]
## 🚀 Feature

Account.createOAuth2Session should return the created sessions

## Have you spent some time to check if this issue has been raised before?

Yes.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes.

## Pitch

We save the current session on the device to be able to log the user out when he clicks the logout button on his account.
It would be nice if `createOAuth2Session` returns the created session to make sure we don't have to get all sessions and search for the newest.

**Comment by lohanidamodar** [comment]
Hi @JulianBissekkou Thank you for creating the issue.

Here are some information that might help you,
1. You can logout by deleting the current session passing session ID as current
2. As createOAuth2Session, is not the function returning the actual session, because it will go through multiple redirects, I am not sure this is even possible at the moment,
3. You can always get the current session as well by passing session id as current while calling `getSession`, new endpoint added in recent version

**Comment by JulianBissekkou** [comment]
Nice!
If you like you can improve the docs on `createOAuth2Session` explaining why this does not return the session and how to get the session that was just created 👍🏽 

Feel free to rename/close this Issue :)
