### ISSUE TITLE
Upgrade on Appwrite with modified docker-compose file

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#1437]
## 🐛 Bug Report

Appwrite doesn't handle upgrading to a new version using a customized `docker-compose.yml` file. Especially when running your own Proxy in front. Meaning removing `traefik` will cause a failed Upgrade.

## Have you spent some time to check if this issue has been raised before?

✅ 

## To Reproduce

- install appwrite
- remove traefik
- upgrade appwrite

## Expected behavior

Upgrading Appwrite.

## Actual Behavior

```
Starting Appwrite installation...
Compose file found, creating backup: docker-compose.yml.1627400322.backup
Service not found
```

**Comment by loftwah** [comment]
@TorstenDittmann I just put together this Docker Compose file that will run Appwrite in HTTP only mode. You can put whatever proxy you like between this, this is also handy with things like ngrok/localtunnel etc

https://gist.github.com/loftwah/9d6ad5f2f895a21688b279fce2b443a3

I haven't submitted a pull request because I don't know where it should be in the directory structure, if it belongs there at all.

Cheers
Dean

**Comment by alexweininger** [comment]
This would save me some time each upgrade!!! 👍 for this feature
