### ISSUE TITLE
Localhost Origin is not Blocked by Appwrite

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#1649]
## 🐛 Bug Report

Appwrite validates origins against the platform list registered for a project, but localhost is always allowed.

## Have you spent some time to check if this issue has been raised before?

I looked through issues, but didn't find anything about this.

## To Reproduce

1. Have a project with no platforms registered
2. Spin up a web app (like the [playground-for-web](https://github.com/appwrite/playground-for-web)) and point it to your project

## Expected behavior

The web app should be blocked because the platform (domain) is not registered

## Actual Behavior

The web app is allowed. This is very dangerous as it allows a bad actor to easily spin up a local web app and mess with the appwrite data. This, coupled with Collection Permission Not Working (https://github.com/appwrite/appwrite/issues/1617) allows a bad actor to create all sorts of bad data.

I suggest only allowing localhost if `_APP_ENV` is development.

## Your Environment

I'm running v:0.10.4.160 in production.

**Comment by TorstenDittmann** [comment]
The platforms are there for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

What you are describing is actually not a concern of CORS, since you can simply do that outside of the browser. So even if we would not add `localhost` by default, it will not prevent bad actors from doing these type of requests.

Since `localhost` is different for everyone, there is no security concern regarding CORS.

You always have to keep in mind, that you cannot add a `user:B` read/write permission when you are `user:A`.
