### ISSUE TITLE
Using 80 port for local docker container. Is it correct?

### ISSUE THREAD

**Issue by toir427** [appwrite/appwrite#2143]
Hello everyone.

https://github.com/appwrite/appwrite/blob/c03bfb66ec4288d78608b2d6e8f883eb2fb4011b/docker-compose.yml#L23-L25

### Why are you using 80 ports?
I am a little bit confused about it because if I use your docker-compose.yml (docker-compose up -d) I have been an error because I have apache on my computer.

![image](https://user-images.githubusercontent.com/19358691/136514695-f0bdf5e9-785b-4a8e-9624-d2179a74c825.png)

**Comment by MichalMaciejKowal** [comment]
@toir427 - as it is mentioned in the docker-compose file:
# WARNING!
# This is a development version of THE Appwrite docker-compose.yml file.
# Avoid using this file in your production environment.
# We're exposing here sensitive ports and mounting code volumes for rapid development and debugging of the server stack.

This file doesn't meant to be used in production. Just create your own docker-compose file with your own configuration for development purposes on your machine because there are too many variables in development environments to accommodate.
