### ISSUE TITLE
Create one project

### ISSUE THREAD

**Issue by amilamen** [appwrite/appwrite#227]
No redirection when I create one project and no alert information which specifies that my project is created. So, when I wait, I ought to create another project before I see my projects.

**Comment by eldadfux** [comment]
Hey @amilamen, thank you for your feedback.

I'll make sure to add a loading screen or message in case project creation takes longer that it needs. I guess this could be pushed to upcoming version 0.4.0

**Comment by amilamen** [comment]
Thanks @eldadfux ! Also, in Getting Started documentation you need to increase version of appwrite in docker command because it is 0.2.0
Just purpose !

**Comment by amilamen** [comment]
Also is it possible to make a documentation with TypeScript ?

**Comment by eldadfux** [comment]
We will be creating a Typescript SDK very soon. This is something that came up a from a few users in the last couple of days and shouldn't be too hard to implement.

**Comment by amilamen** [comment]
Greatfully ! Me and my collegue https://github.com/ChafikHadjAbdouRazack are available to work with you on project.

**Comment by amilamen** [comment]
A simple curiosity, why you don't use a popular framework like Laravel and you prefer to make your own framework ?

**Comment by eldadfux** [comment]
> Thanks @eldadfux ! Also, in Getting Started documentation you need to increase version of appwrite in docker command because it is 0.2.0
> Just purpose !
Fixed

**Comment by eldadfux** [comment]
> A simple curiosity, why you don't use a popular framework like Laravel and you prefer to make your own framework ?

This is a very long and complex topic to discuss, and I don't want to get too much off-topic, so I'll try to answer shortly.

First of all, building your own framework is not always the smartest thing to do. In most cases, it isn't.

We built the Utopia framework because we wanted to get more flexibility and better enforcement of security using code. 

Utopia declarative approach helps us gain both. We are heavily reliant on Utopia for code automation in areas like service abuse protection, security controls, and documentation & SDK generation. Utopia helps us force our standards using code and have better code visibility using her declarative approach to code. 

We wanted to achieve better harmony between Appwrite different components, and this was one way to get there.

This is a risk we took, and for this point in time, it seems to pay off. That said, Utopia still needs to prove herself in the long run, and we hope it would be able to stand for herself as an independent project.

**Comment by amilamen** [comment]
Thanks you dear ! It is an awesome project and easy for using. Very good job !

**Comment by eldadfux** [comment]
Thank you ❤️

**Comment by eldadfux** [comment]
This commit https://github.com/appwrite/appwrite/commit/fb9adf31d9c2bb3286ba253ac1618d5aaec86b68 will adds a loading message and fixes the broken redirect URL when creating a new project.

**Comment by eldadfux** [comment]
This fix is already available on the master branch and will be released with version 0.4.0

**Comment by amilamen** [comment]
Very god job sir !
