### ISSUE TITLE
📚 Documentation: The teams documentation is riddled with errors

### ISSUE THREAD

**Issue by rdmchr** [appwrite/appwrite#2359]
### 💭 Description

The Teams documentation (https://appwrite.io/docs/client/teams) contains a lot of errors. Here are some examples:

https://appwrite.io/docs/client/teams#teamsCreateMembership: 
> If initiated from server side SDKs, new member will automatically be added to the team.

> While calling from side SDKs the redirect url can be empty string.

https://appwrite.io/docs/client/teams#teamsGetMemberships:
> Get a team members by the team unique ID.

https://appwrite.io/docs/client/teams#teamsDelete:
> Only team owners have write access for this resource.

I think there are some more, but I think those examples are enough to show, that the Teams documentation is in need of an overhaul. Furthermore, is https://appwrite.io/docs/client/teams#teamsUpdateMembershipRoles completely missing a description.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by kodumbeats** [comment]
Yeah, let's clean this up. @rdmchr Would you like to collaborate on these changes? 

The endpoint descriptions are found in markdown files under [`/docs/references/teams`](https://github.com/appwrite/appwrite/tree/master/docs/references/teams), while the parameter descriptions are defined in-line in the [`/app/controllers/api/teams`](https://github.com/appwrite/appwrite/blob/master/app/controllers/api/teams.php).

For the `updateMembershipRoles` route, it seems we haven't created the necessary markdown file (`/docs/references/teams/update-team-membership-roles.md`).

**Comment by kodumbeats** [comment]
@rdmchr Let's start by updating the issues you've highlighted. Since you're not familiar with PHP, I'll show you how to find the source file for the docs changes. 

Using `/docs/client/teams#teamsCreateMembership` as an example - the docs say the route is `/v1/teams/{teamId}/memberships`. First, find the corresponding route in `app/controllers/api/teams.php` - the syntax feels like Express.js to me:
https://github.com/appwrite/appwrite/blob/0e91b67528d10716ea328421577e8a2f71e427b3/app/controllers/api/teams.php#L249-L258
Each route has an `sdk.description` label, identifying where the doc source is - in this case:
https://github.com/appwrite/appwrite/blob/0e91b67528d10716ea328421577e8a2f71e427b3/app/controllers/api/teams.php#L258
So this is the file we need to edit:
https://github.com/appwrite/appwrite/blob/0e91b67528d10716ea328421577e8a2f71e427b3/docs/references/teams/create-team-membership.md#L1-L5

If, for instance, we needed to update the documentation for a parameter on the route, you can see it in code:
https://github.com/appwrite/appwrite/blob/0e91b67528d10716ea328421577e8a2f71e427b3/app/controllers/api/teams.php#L263-L267

**Comment by rdmchr** [comment]
Ah, I see, that makes sense. I'll get started on this tomorrow. Be ready for a ping on Discord if I encounter a problem, but I think your guide seems pretty intuitive so far 😉

**Comment by rdmchr** [comment]
@kodumbeats I need your help again :smiled:  https://appwrite.io/docs/client/teams#teamsUpdate says "Only team owners have write access for this resource." but there is no such check in the code, right? https://github.com/appwrite/appwrite/blob/master/app/controllers/api/teams.php#L169-L204 It would also contradict the doc at https://appwrite.io/docs/client/teams#teamsCreate where it says "The team owner can invite new members, who will be able add new owners and update or delete the team from your project.":NM_PeepoDetective:
same for the Delete team endpoint, btw :)

oh and I think I messed up the order of the naming convention for my branch name. https://github.com/appwrite/appwrite/pull/2397 should I just create a new pr?

**Comment by kodumbeats** [comment]
In Appwrite, everything stateful is a document - users, teams, collections, functions, etc. are all saved as a document in the database, and the same permission system used in the Database service is also used internally. 

So, to see the permissions of a team, we can look at the permissions set when the resource is created. For a team, we can look in `POST /v1/teams`: 
https://github.com/appwrite/appwrite/blob/a1a4584095768f25b616ffa53bfee417c866c541/app/controllers/api/teams.php#L52-L61
So, a team document should be readable by all in the team, but changes to the team can only be performed by those in the `/owner` role.

> oh and I think I messed up the order of the naming convention for my branch name. #2397 should I just create a new pr?

It's okay for this PR, since it's coming from your personal fork. It matters more for maintainers working directly from the Appwrite repo. :)

**Comment by rdmchr** [comment]
I have completed the update. Please let me know if you want me to change anything.
