### ISSUE TITLE
🚀 Feature: Hide function environment variables by default

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2388]
### 🔖 Feature description

Hide the secret values by default with a button to display them. Actually, most platforms don't provide a way to see the value, the button to show it might not be necessary (and more secure).

![CleanShot 2021-11-03 at 11 34 59](https://user-images.githubusercontent.com/19310830/140045695-32e9fc69-2094-4f94-b175-a2cf38567ebe.png)

### 🎤 Pitch

Looking at any huge company, they all hide secrets by using `******`. Reasons:

1. If I want to show function settings to someone, I don't want to show him the actual values of environment variables
2. If I share a project with a team member, I don't want him to seethe secrets

Depending on which scenario we want to solve, we can either hide value and provide a show button, or hide it with no way to see it.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by kodumbeats** [comment]
❤️ my first `appwrite/appwrite` PR added a Litespeed component that does this: https://github.com/appwrite/appwrite/pull/791

_My thoughts:_

This component probably wasn't used here because not all function envs have to be secrets - config envs come to mind first. 

I think it'd be an easy lift to add this now by using the `data-forms-show-secret` component on the input fields, but that wouldn't be ideal for the use case of configs as envs. The best DX would be to separate them into different options, but that'd be a heavier lift.

**Comment by stnguyen90** [comment]
👍  for options for sensitive vars vs non-sensitive that would ideally be encrypted.

**Comment by eldadfux** [comment]
> 👍 for options for sensitive vars vs non-sensitive that would ideally be encrypted.

Right now we encrypt all options. Would it be too bad to hide all fields no matter what by default?
I see this patterns repeating in many services (Travis CI, Github Actions), don't really see the harm, at least on the Functions context.

**Comment by wess** [comment]
Could make the value fields have the eye-icon toggle button to flip type between "password" and "text" like login forms do now.
