### ISSUE TITLE
🐛 Bug Report: accounts.create does not get trigger function on account created with OAuth provider

### ISSUE THREAD

**Issue by matfire** [appwrite/appwrite#2406]
### 👟 Reproduction steps

- Create a function that should get triggered on accounts.create
- Deploy tag (my use case was creating a document in a collection)
- Create an account with email and password from a web frontend (React in my specific case)
- Function should get triggered
- Create another account using an Oauth provider (Google in my case)
- Function should not get triggered

### 👍 Expected behavior

Function should get triggered in both cases, when an account is created using email + password and when using a third party provider (Google, Github etc)

### 👎 Actual Behavior

Function gets triggered only when creating an account using email and password

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite v:0.11.0.170

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by JaviBonilla** [comment]
I’m also having the same issue.

**Comment by PineappleIOnic** [comment]
I'm on the case 👍

**Comment by garvitomer** [comment]
Is this issue solved in 13.4 or it is still there? Last I checked it was there in 12.x versions

**Comment by stnguyen90** [comment]
@PineappleIOnic, looking at the code, it looks like the user is created, but no new user event is triggered:

https://github.com/appwrite/appwrite/blob/648b6f2038fb59b2beb78d81cea08aa730a106c3/app/controllers/api/account.php#L466-L501

**Comment by karniv00l** [comment]
I think this issue also exists when creating a user using Magic URL

**Comment by ddenev** [comment]
@stnguyen90 , can this be prioritized higher?

I see this has been lagging since 0.16 milestone but currently this bug prevents me from using Google OAuth2 in my app.

Thank you!

**Comment by garvitomer** [comment]
Use 'session.create' for time being, I am also using the same.

**Comment by t0mm4rx** [comment]
Still an issue with Magic URLs. Checking for session creation with some sort of state is possible but not ideal.

**Comment by moshOntong-IT** [comment]
What is the status for this issue?

**Comment by moshOntong-IT** [comment]
We should consider introducing a new method named createOAuth2.

The primary objective of this method is to facilitate sign-up using an OAuth2 provider. When this method is invoked, the backend will recognize the user as a new one, subsequently triggering the appropriate event.

On the other hand, the existing method, createOAuth2Session, is solely for signing in or establishing a session with the OAuth provider. If the account does not exist, it should return a "404 Not Found" error, rather than automatically creating a new account.

**Comment by PratikDev** [comment]
Hey, what's the status of this issue?

**Comment by tdansie** [comment]
Also checking in on the status so that we can implement Google oauth

**Comment by ItzNotABug** [comment]
Subscribing to this.

**Comment by limes** [comment]
Hey, is it fixed in 1.5?

**Comment by Whitehat645** [comment]
@stnguyen90  this is basic feature needed for everyone as there is no way to execute a function to send a welcome email, and do some reservations in the databases, this bug prevents Appwrite users for using the OAUTH and other login functionalities itself.

**Comment by MaximSedov** [comment]
Not fixed in 1.6.0?

**Comment by ddenev** [comment]
@eldadfux , @stnguyen90 - could you please prioritize this for fixing? It's a shame - reported 3 years ago and still no fix!

This renders OAuth2 authentication almost useless for Appwrite since we need to act on user create events (see https://github.com/appwrite/appwrite/issues/2406#issuecomment-2262062286).

Pumping new features is nice but Appwrite is now in production, so you have to properly monitor and take care of bugs as well

Please bring this to the fixing queue.

Thank you!

**Comment by Gincioks** [comment]
Subscribing

**Comment by samuelbushi** [comment]
The trigger does not work with wither OAuth providers, magic links, or email OTPs.

**Comment by ugurcany** [comment]
Currently, email OTP auth does not trigger a function that's listening to the events `users.*.create`. It's a serious bug that affects many live products using Appwrite.

**Comment by eldadfux** [comment]
Finally! Fixed!. This should already be live on Cloud and will also be part of the next release for self-hosting. If you notice any more issues please let us know.
