### ISSUE TITLE
🐛 Bug Report: adding a platform does not change Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by superseby2** [appwrite/appwrite#2464]
### 👟 Reproduction steps

- add a platform
- using https://custom.hostname.com/

- curl -vv -H"Origin: https://custom.hostname.com/" -H 'X-Appwrite-Project: xxxxxxxxx' "https://<domainname>/v1/account/sessions/oauth2/linkedin"

### 👍 Expected behavior

- Having a response with headers  (and being able to perform CORS-enabled xhr)

Access-Control-Allow-Origin: https://custom.hostname.com/

### 👎 Actual Behavior

I am seeing : 

- Access-Control-Allow-Origin:  https://localhost

(and get CORS exeptions when running form browser)

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite is behind nginx which does basic proxy with no particular manipulation.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
`localhost` is returned as allowed origin if your origin is not allowed. But you allowed it, right?

You specified hostname to be `https://custom.hostname.com/`, but we are only expecting domain here - no protocol, no port, no path. Since you provided additional stuff, our security layer did not recognize the hostname.

By setting platform hostname to `custom.hostname.com`, the problem should be fixed and you should start receiving selected allow-origin headers.

Please let me know if this solved your problem. I was able to replicate and solve it this way.

**Comment by superseby2** [comment]
Thanks for getting back to me so quickly and sorry for the delay for my response. 

I had tried with and without the 'http://' part to no avail. Then "it just worked" ..  So I will dig a little deeper to try to reproduce the problem and the solution and get back to you. 

Thx!

**Comment by Meldiron** [comment]
Hello @superseby2 👋

Did the solution work for you? If so, please let's close the issue. If it didn't, please let me know and we can dig deeper into your problem.

**Comment by Meldiron** [comment]
Cloding the issue due to inactivity. Feel free to re-open if the problem persists.
