### ISSUE TITLE
🐛 Bug Report: Teams: getMemberships throws 'Team not found'

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#2581]
### 👟 Reproduction steps

after migration from 0.11 to 0.12 users with teamrole member are not able to retrieve memberships of their own team.

this issue only happens with teams from before migration.
new teams are working fine.

in the docker logs i found this:
```
[Error] Timestamp: 2022-01-08T21:51:02+00:00
[Error] Method: GET
[Error] URL: /v1/teams/:teamId/memberships
[Error] Type: Utopia\Exception
[Error] Message: Team not found
[Error] File: /usr/src/code/app/controllers/api/teams.php
[Error] Line: 449
```

### 👍 Expected behavior

members of migrated teams should be able to retrieve other memberships like in 0.11 before

### 👎 Actual Behavior

only owners are able to retrieve memberships from migrated teams

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Wasn't this resolved in 0.12.1?

**Comment by s3ppo** [comment]
> Wasn't this resolved in 0.12.1?

I am not sure, it seems new to me.. i can reproduce it every time i try it.

First i thought its only to existing documents that i want to update but its also to totally new documents that i want to create

**Comment by stnguyen90** [comment]
> First i thought its only to existing documents that i want to update but its also to totally new documents that i want to create

Documents? Isn't this issue about Team Memberships?

**Comment by s3ppo** [comment]
Sorry bro 😅 i was in the wrong issue 😂

**Comment by TorstenDittmann** [comment]
Found the culprit and its an easy fix luckily. This will be taken care of in the migration.

As seen on this file https://github.com/appwrite/appwrite/blob/0.12.2/src/Appwrite/Migration/Version/V11.php#L665-L666 there was a typo when migrating the permissions.

What this results in, that the `$read` permissions have the wrong role.

So basically what needs to be done is removing the owner from from the `$read` permissions on the team document.

```diff
$read: [
-   'team:XXX/owner'
+.  'team:XXX'
]
$write: [
    'team:XXX/owner'
]
```

This will be taken care of in the migration for the next version and a 0.12.x release, sadly its not that easy to migrate this with 0.12.x if you already have migrated from 0.11 - since it might overwrite stuff when running the migration a second time.

# Hotfix
A hotfix look for instances that already got migrated from 0.11 to 0.12:

> Always backup your Database/Instance before you run any of the following commands!!!

```sql
UPDATE `_project_PROJECTID_teams` SET `_read` = replace(_read, '\\/owner', '');
```
easy to execute command:
```sh
docker compose exec mariadb mysql -u USER -p appwrite -e "UPDATE \`_project_PROJECTID_teams\` SET \`_read\` = replace(_read, '\\\/owner', '');"
```
- **USER** needs to be replaced with the db user
- **PROJECTID** needs to be replaced with the project ID

To reflect these changes in Appwrite, also the cache needs to be cleared:
> CAREFUL! If there are any background jobs running - they will be removed from the queue. So make sure Appwrite is not doing any work at that moment.
```sh
docker compose exec redis redis-cli FLUSHALL
```

I'll be more than happy to help out and assists applying the hotfixes, so feel free DM me on our [Discord](https://appwrite.io/discord).
