### ISSUE TITLE
🐛 Bug Report: Deleted account isn't deleted

### ISSUE THREAD

**Issue by stonith404** [appwrite/appwrite#2623]
### 👟 Reproduction steps

1. Create an account
2. Sign in with the account
3. Delete the account from the console
4. Try to run `user.get()`

As you can see the user isn't listed anymore in the Appwrite dashboard but the function `user.get()` still returns e.g the uid. 

### 👍 Expected behavior

`user.get()` should fail because the user was deleted

### 👎 Actual Behavior

`user.get()` doesn't fail. This could mean, that the user isn't really deleted, only hidden from the console.

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by am283721** [comment]
Just ran into an issue where I deleted a user via the appwrite dashboard, tried to recreate the user in my app and received an "Account already exists" error. I took a look through PRs and issues and found this. Sounds like it might be the same root cause.

Assuming it hasn't been fixed since reporting this issue, I might try and take a look.

**Comment by stnguyen90** [comment]
@stonith404, the [Delete](https://appwrite.io/docs/server/users?sdk=nodejs-default#usersDelete) API has been updated to fully delete the user, including the ID. Can this be closed now?
