### ISSUE TITLE
Added some vars to .env, ran docker-compose restart, now stuck in init/cert loop in terminal

### ISSUE THREAD

**Issue by locohost** [appwrite/appwrite#2664]
As title says, I added a couple vars to the appwrite .env. Tried to use them in my function and got undefined errors. So I thought I probably have to restart appwrite. I ran docker-compose restart. Is this my error? Is there another way to restart appwrite?

Now my console web app SSL cert is invalid...

![image](https://user-images.githubusercontent.com/132458/150574384-8e7e8042-c00d-49f8-9b90-58b42b60b6c8.png)

And now in terminal, trying to use the CLI and its stuck in a "you have to init, now you have to cert" over and over loop somehow...

![image](https://user-images.githubusercontent.com/132458/150574903-b0e69935-ccc7-4bbc-940e-f619d8094318.png)

I guess running docker-compose restart was completely wrong. How do I recover from above?

Thank you for helping :-)

---
Appwrite Version: 0.12.0.200

**Comment by eldadfux** [comment]
Not sure I have enough data to try and help because this seems like a mix of multiple issues. We have just added some instructions on how to stop and remove Appwrite here: https://appwrite.io/docs/installation

After successfully removing the setup, you can install it again, and for the record and future devs who might reach this page, `docker-compose restart` should work fine and is a legit way to restart Appwrite. 


![image](https://user-images.githubusercontent.com/1297371/150732101-da15f82c-285e-40ca-8aff-0e246d57e644.png)
