### ISSUE TITLE
Appwrite CLI - installation error

### ISSUE THREAD

**Issue by tsrift** [appwrite/appwrite#2667]
This command for installation the CLI produces error:
`curl -sL https://appwrite.io/cli/install.sh | bash`
The docker daemon is not operational. Make sure that docker is running and try again.

Installation of appwrite was done previously with the Docker installer tool.

![cli](https://user-images.githubusercontent.com/47740602/150619890-53c63355-3bd6-44da-91e9-2b55d5675f4e.png)

**Comment by eldadfux** [comment]
You need to make sure you have Docker installed and **running** on your setup.

**Comment by superseby2** [comment]
Got the same error. Had to run the command as sudo to pass the test relative to docker.

**Comment by tsrift** [comment]
The command for installation has to be with sudo, it should be stated in Docs tutorial:
`sudo docker run -it --rm     --volume /var/run/docker.sock:/var/run/docker.sock     --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw     --entrypoint="install"     appwrite/appwrite:0.12.1`

So, Appwrite is installed and it's working but installation of the CLI is not working. I tried also with sudo but it' the same:
`sudo curl -sL https://appwrite.io/cli/install.sh | bash`

**Comment by tsrift** [comment]
Docker is running.
![docker](https://user-images.githubusercontent.com/47740602/150794212-63a4bc78-f209-4569-9d01-48b8fb4b5232.png)

**Comment by superseby2** [comment]
You are sudoing the curl command IMHO try to curl -sL <URL> -o install.sh 
then sudo bash install.sh

Otherwise, I guess, that if you configured everything on your system to run docker stuff from a regular user you should be able to run the cli install from a regular user.  (as the cli install is needs to access /var/run/docker.sock to determine whether docker is locally running. I just did not bother to do it on my system hence the sudo shortcut ;)

check here how to do this https://www.tutorialspoint.com/running-docker-container-as-a-non-root-user

**Comment by tsrift** [comment]
I tried this.
`curl -sL https://appwrite.io/cli/install.sh | sudo bash
`

![sudo bash](https://user-images.githubusercontent.com/47740602/150797787-9676d81e-514d-4c81-b994-8e5c1f73ab44.png)

**Comment by eldadfux** [comment]
Your Docker doesn't seem to work. The next version of the CLI (v2.0) will be packaged as an OS binary and you won't need the Docker dependency anymore.

**Comment by eldadfux** [comment]
The new Appwrite CLI (2.0) doesn't need Docker anymore.
