### ISSUE TITLE
🐛 Bug Report: Error 500 creating collection

### ISSUE THREAD

**Issue by aymericfontaine** [appwrite/appwrite#2814]
### 👟 Reproduction steps

Cannot create collection with 'post' id.
I tried in the web interface and in the CLI.

### 👍 Expected behavior

I previously deleted the 'post' collection. I think there are traces left somewhere.

### 👎 Actual Behavior

I get an error 500 when I create the collection 'post'

![image](https://user-images.githubusercontent.com/39033239/154816186-e323a0ba-57ac-4fff-8891-c9930713c693.png)

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Fresh install of Docker and Appwrite images.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by aymericfontaine** [comment]
![image](https://user-images.githubusercontent.com/39033239/154816374-24fbde00-c1a7-4c41-8187-ae58517ccb39.png)
Note that getQueueUsage only increases.
It's normal ?

**Comment by outrelouxhe** [comment]
I have experienced this bug several times without knowing how to fix it. By looking in the logs, it usually says something like `Duplicate key name _index2`. I See that Aymeric was able to solve it by updating manually MariaDB. In the meantime until this bug is fixed, it would be nice to have more detailed instructions on how to repair the database. I'm not familiar with MariaDB so if America or anybody else could provide some instructions, I would be very pleased, because when I have this bug I need to erase everything and start from scratch again. Thank you!

**Comment by aymericfontaine** [comment]
@outrelouxhe 
This is what I do when I have the problem:

**1. MariaDB database dump**
`docker exec appwrite-mariadb sh -c 'exec mysqldump --all-databases --add-drop-database -u"root" -p"$MYSQL_ROOT_PASSWORD"' > ./dump.sql`

**2. Identification in the dump of references to the index in error** 
CTRL + F in the dump with index name. Be careful to ignore lines that do not refer to an index. I recommend naming its indexes so as to identify them well

**3. Prepare deletion query**
`DELETE [TABLE_NAME] WHERE _id IN ([IDS_REF_INDEX]);`
`DROP INDEX [INDEX_NAME] ON [TABLE_NAME];`

**4. Connect to MariaDB and exec deletion request**
`mysql -uroot -p"$MYSQL_ROOT_PASSWORD"`
Execute query

**Comment by TorstenDittmann** [comment]
iirc this issue was addressed with 0.13.0 and fixed.
