### ISSUE TITLE
what is the last production stable version?

### ISSUE THREAD

**Issue by matigumma** [appwrite/appwrite#3026]
what is the last production stable version
im trying to  implement for my project

**Comment by Meldiron** [comment]
We always recommend going with the latest version, which is `0.13.4` at the moment. Appwrite is already stable, we are in `0.x.x` because we still might do some breaking changes to improve the quality of Appwrite. Don't worry tho, we always prepare proper migration scripts, migration guides, and are always available on [Discord](https://appwrite.io/discord) to provide help.

**Comment by matigumma** [comment]
thanks!
