### ISSUE TITLE
🐛 Bug Report: Error when uploading small mp4 video file

### ISSUE THREAD

**Issue by istornz** [appwrite/appwrite#3037]
### 👟 Reproduction steps

- Create a new bucket with settings:
  - Maximum File Size: **90000000**
  - Enabled: **Yes**
  - Encryption: **Yes**
  - Anti Virus: **Yes**
  - Allowed File Extensions: **mp4**
  - Read Access: **role:all**
- By using web console, or API, just upload a **.mp4 video** of 2.8Mo

Appwrite logs show:
```
[Error] Message: Error bucket maximum file size is larger than _APP_STORAGE_LIMIT
```

FYI, .env file was not modified & show for _APP_STORAGE_LIMIT
```
30000000
```

I tried to disable AV but nothing works...

### 👍 Expected behavior

Upload the file & show success message

### 👎 Actual Behavior

File was not uploaded & show failed

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Ubuntu

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
The issue here is that on the bucket you tried to configure a 90MB limit, while the server only allows 30MB. That resulted in an unexpected error, as the controller was checking 90MB max size on the 30MB instance limit.

A quick solution is to set the size on the bucket to less or equal to the number set as a limit in `.env`.

I will work on a PR to address this, not allowing to configure such a size limit on bucket that would be bigger than instance limit.

**Comment by istornz** [comment]
@Meldiron thanks for your answer, I can confirm that changing in ```.env``` file the limit to 90Mb works 🤗
