### ISSUE TITLE
🐛 Bug Report: Query for integer value with 0 not working

### ISSUE THREAD

**Issue by s3ppo** [appwrite/appwrite#3071]
### 👟 Reproduction steps

if i query for an integer with a value of 0, my listDocuments returns me total: 0 but there are a lot of 0 integer values in my collection.

does not work:
```
queries.add(Query.equal('intValue', 0));
```

is working fine:
```
queries.add(Query.equal('intValue', 1));
```

### 👍 Expected behavior

it should listDocument me all documents from my collection with an value of 0

### 👎 Actual Behavior

no documents are found with value 0

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
I did some tests with an equal filter on the integer and it sort of works. I did get some documents back, but there were others I expected to get back that didn't. It turns out the database has NULL instead of 0 for those documents that weren't returned even though the API returns the values as 0. 

With query:

![image](https://user-images.githubusercontent.com/1477010/162600066-ab793874-1b6e-4c44-b037-4ecc44b32dfb.png)

Documents in database:

![image](https://user-images.githubusercontent.com/1477010/162600036-de0bc189-6f12-4b9c-af4e-cdab8a01cc42.png)

Without queries:

![image](https://user-images.githubusercontent.com/1477010/162600025-989314cb-7638-4b85-957c-0ebdb097850e.png)

If I create a new collection and new documents, all the documents are returned as expected.

**Comment by TorstenDittmann** [comment]
Looks like we do not respect `NULL` values from the Database and return them as `0`.

That might affect other attributes as well.

**Comment by christyjacob4** [comment]
@s3ppo  Thanks for raising this. We are taking a look 👍

**Comment by lohanidamodar** [comment]
Well, found the source of the problem, creating a fix
https://github.com/utopia-php/database/blob/6507b58ef3e22703b9df68d3dbd5e822d5bb023f/src/Database/Database.php#L1197
