### ISSUE TITLE
Named documents

### ISSUE THREAD

**Issue by cweagans** [appwrite/appwrite#312]
For the most part, I could get by with the document IDs being auto generated, but there are a few cases where that doesn't work very well.

For instance, if I wanted to store and load some app preferences for a particular user account, it would be create to explicitly say "this document is the preferences document and I can only have one". Maybe it's an optional param for https://appwrite.io/docs/database#createDocument. Then, on https://appwrite.io/docs/database#getDocument, I could load that same document by name.

I could work around this by creating a named collection and only ever insert one document into it, but that seems a little hacky.

**Comment by eldadfux** [comment]
You can overcome this issue in two ways:

1. Use the account prefs route to save user specific data like this:

```
let sdk = new Appwrite();

sdk
    .setProject('5df5acd0d48c2') // Your project ID
;

let promise = sdk.account.updatePrefs({
    'gender': 'female',
    'age': 30,
    'prefsDocument': '5df5ac473847' // or even have a ref to your settings doc
});

promise.then(function (response) {
    console.log(response); // Success
}, function (error) {
    console.log(error); // Failure
});
```
Spec is here: https://appwrite.io/docs/account#updatePrefs

2. Like you said you can add only one document per user in that collection, but you could use the documents list route to fetch only one document instead of an array (using the "first=1" parameter) and this will be a bit less hacky.

Spec is here: https://appwrite.io/docs/database#listDocuments

**Comment by cweagans** [comment]
Just saw this. Thanks for the info!
