### ISSUE TITLE
Add blurha support for image

### ISSUE THREAD

**Issue by duythien0912** [appwrite/appwrite#328]
Can you support https://blurha.sh/

**Comment by eldadfux** [comment]
Hey @duythien0912 how would you see this integrate with Appwrite? Please provide more info

**Comment by duythien0912** [comment]
I think we can add new params name blurha on view image link  

`http://appwrite.io/v1/storage/files/{fileID}/view?project={projectID}&blurha={blurHash}`

blurhash string will create when we upload the image ( maybe on flutter or server )

**Comment by eldadfux** [comment]
I don't think this should be added to the storage service because its a a very specific feature that might add more complexity, especially when talking about integration with a 3rd party service.

This can be a really good fit for our cloud functions service. We could create a function that listens to any file uploaded, get the image string from blurHash and save it as new meta data for the file or any related database document for max performance.

**Comment by eldadfux** [comment]
You can read about our cloud functions feature here: #307

**Comment by christyjacob4** [comment]
@duythien0912 Thanks for this idea. But we're trying to make appwrite APIs interact with as less 3rd parties as possible. We only interact with 3rd party providers for our OAuth endpoints which would be impossible to implement otherwise. 

As @eldadfux suggested it's best to use the cloud functions service.
