### ISSUE TITLE
SMTP disabled upon member in team creation

### ISSUE THREAD

**Issue by MichalNemec** [appwrite/appwrite#3283]
Hello,
_APP_SMTP_HOST - SMTP server host name address. Use an empty string to disable all mail sending from the server. The default value for this variable is an empty string

i have this empty and i cannot add member to a team.. Another thing, why i have to add email, it could autocomplete user which is already created.

Or is there any other way how to make rbac (customer/editor/admin)?

---
Appwrite Version: 0.13.0.300

**Comment by stnguyen90** [comment]
> i have this empty and i cannot add member to a team.. 

To add a user to a team without sending an email, use the [Server API](https://appwrite.io/docs/server/teams?sdk=nodejs-default#teamsCreateMembership). For now, to bypass the [env var check](https://github.com/appwrite/appwrite/blob/426449d1d8cc9e80e0e115e7831dadf66a16c905/app/controllers/api/teams.php#L300), set the env var to something other than empty string.

> why i have to add email

This is mostly for the Client API since clients probably won't know a user's ID. That said, I do think it would be useful to expose a Server API to add a user to a team using user ID.

> it could autocomplete user which is already created

I definitely don't think this is a good idea to do client side because it would allow a bad actor to scrape all user emails in an Appwrite instance.

**Comment by 0xTux** [comment]
> > i have this empty and i cannot add member to a team..
> 
> To add a user to a team without sending an email, use the [Server API](https://appwrite.io/docs/server/teams?sdk=nodejs-default#teamsCreateMembership). For now, to bypass the [env var check](https://github.com/appwrite/appwrite/blob/426449d1d8cc9e80e0e115e7831dadf66a16c905/app/controllers/api/teams.php#L300), set the env var to something other than empty string.
> 
> > why i have to add email
> 
> This is mostly for the Client API since clients probably won't know a user's ID. That said, I do think it would be useful to expose a Server API to add a user to a team using user ID.
> 
> > it could autocomplete user which is already created
> 
> I definitely don't think this is a good idea to do client side because it would allow a bad actor to scrape all user emails in an Appwrite instance.

I've used the server API to add a user to my team. The newly added user is showing as pending in my member's tab and upon logging into the new account the organizations tab is still empty.

![image](https://github.com/appwrite/appwrite/assets/97862450/0f4617ee-00d5-4fdf-91d5-f809b041de7b)

![image](https://github.com/appwrite/appwrite/assets/97862450/85ac51ca-2276-43d0-b616-22f3b0fd0030)
