### ISSUE TITLE
🚀 Feature: Clear logs

### ISSUE THREAD

**Issue by radvansky-tomas** [appwrite/appwrite#3284]
### 🔖 Feature description

There should be simple button to clear logs

### 🎤 Pitch

Function execution, specially for trigger function becomes messy and there should be easy way to delete and probably even search in them.

Might be even better to provide 1 line/brief from output/error...so you dont have to go one by one...look at this:
<img width="1445" alt="Screen Shot 2022-05-26 at 5 40 39 PM" src="https://user-images.githubusercontent.com/12473664/170423985-5d532165-fa35-447a-9ea4-4aeddf3231d0.png">

This is nightmare, 5 pages of same entries....imagine finding there something...

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Hello 👋

Function logs as well as document audits are kept for up to 14 days on the default installation. We decided to introduce this feature mainly because it doesn't cost too much performance and can help **A LOT** with the administration of your app. It feels like a feature that allows you to _see the history_.

With that said, in your `.env`file, you can decrease `_APP_MAINTENANCE_RETENTION_EXECUTION` to clear these logs more often.

---

I don't think it's a good idea to have a button to delete them, but I agree with you it can get tricky trying to find what you are looking for if you have many executions. One idea that comes to my mind is allowing filtering of logs by date and status (successful or not). Do you think these would help you with your use case? If not, what other sorting/filtering mechanisms can you think of that would help you find needed log?

**Comment by radvansky-tomas** [comment]
Your question is very related to this one https://github.com/appwrite/appwrite/issues/3295

I mean its basically impossible to get meaningful logs from that screen. I always end up reading docker logs from container. Which obviously get's killed after execution. 

So yeah, there needs to be a way to get your logs there + add filtering + add level + add search. 

As this is often compared to firebase:
- logs pickup stdout logs
- pickup level
- pickup executed function
- timestamp
- you can make structured errors/logs

**Comment by stnguyen90** [comment]
@radvansky-tomas instead of clearing logs, how about we use this issue for adding filters or something to help sort through logs?

**Comment by eldadfux** [comment]
The upcoming release for function will include an option to turn logs off. In the next iteration we do plan to improve the UI and add filtering options.

**Comment by eldadfux** [comment]
As of today, Appwrite cleans your logs every 1h, 7d, 28d or 90d depending on your plan. You can also disable functions logs from your function settings.
