### ISSUE TITLE
New feature : Create a collection directly in Dart from Client side

### ISSUE THREAD

**Issue by sylvainjack** [appwrite/appwrite#3301]
It would be great if you added a similar function to create.document, but applied to collection. Create.collection. It would help a lot as it would let us create and therefore "name" a collection programmatically. It would make it so much easier to structure our datas. Is it possible ?

**Comment by stnguyen90** [comment]
This is possible already with a server SDK like that dart one: https://appwrite.io/docs/server/database?sdk=dart-default#databaseCreateCollection.

**Comment by sylvainjack** [comment]
I had tried that, but dart tells me database.createCollection isn't defined for the database...

**Comment by stnguyen90** [comment]
Yes, Appwrite has 2 types of [SDKs](https://appwrite.io/docs/sdks): Client and Server. 

Client SDKs are used in client side apps and interact with Appwrite as an end user. 

Server SDKs are meant to be used server side. When used with an API key, they allow for admin access such as creating Collections.

**Comment by sylvainjack** [comment]
Hmmm. So question : from my flutter app, is there a way for me to create collections ?

**Comment by 2002Bishwajeet** [comment]
Not at this moment. You can create collections using the server side SDK or from the appwrite Dashboard itself

**Comment by sylvainjack** [comment]
Bad news for me... as as I just added in my last message : the collections should be created following a user's action... It would be such a great feature if we could do this... any chance the team of developers would be interested in adding this feature ? I used to do that with Firebase and it gives us so many possibilities....

**Comment by 2002Bishwajeet** [comment]
Could you explain a particular use case, why would you want to create a collection from the client side. That being said, you should open a discussion page to talk more about it with the core maintainers

**Comment by natgross** [comment]
This is a basic capability of other database clients. We create Collections AND Databases on the fly -all the time-. 
I think the problem here is [perspective] that the aw team is looking at  a Database like this Oracle SQL db, with tables, etcetera, clearly an admin job. 
Whereas in the MongoDB & Couchbase world, a db and a collection is no big deal, dynamically created per user's choices and other requirements. I am not comparing you to other db's, just explaining this one point. Tons of use-cases where I create collections on the fly, and sometimes a db as well.

**Comment by danibjor** [comment]
Creating collections from the client opens up a whole new set of security concerns. 

I'm not saying that there are valid use cases for this, but could a possible solution for you be to trigger a function that does this work? You can do what you ask from the server side SDK, and this also allow you to enforce rules without exposing too much to the client side.

**Comment by natgross** [comment]
> Creating collections from the client opens up a whole new set of security concerns.
Agreed!
Therefore this: https://github.com/appwrite/appwrite/issues/3613

**Comment by stnguyen90** [comment]
Closing as adding capability to create collections client side would open security concerns. 

The recommended approach for creating collections at at runtime is to use Appwrite Functions. This will at least restrict what collections and attributes an end user can create rather than giving them access to create anything.
