### ISSUE TITLE
🚀 Feature:  Add Soundcloud OAuth Provider

### ISSUE THREAD

**Issue by 2002Bishwajeet** [appwrite/appwrite#3354]
### 🔖 Feature description

Sound is a music streaming app where is lets people discover and enjoy the greatest selection of music from the most diverse creator community on earth. 

It would be nice to have a SoundCloud OAuth Provider added in the current list of OAuth providers.

I checked their [docs](https://developers.soundcloud.com/docs#authentication) and I believe we could add this.

### 🎤 Pitch

It's a popular music streaming app and its being used by millions of people over the world. It could be useful to have this OAuth provider where a user could directly log in from Souncloud OAuth.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
> I browsed a bit through their docs, they don't seem to expose user's email after authentication.
> 
> Is there any other info which could replace the need of user's email and thus could be implemented??

I tried to tackle this issue with a different provider. My proposed solution was to create an unexisting domain as an email replacement, and use the user's ID in it: https://github.com/appwrite/appwrite/blob/feat-trackmania-oauth/src/Appwrite/Auth/OAuth2/Trackmania.php#L135

The solution was not liked by the maintainer's team, mainly because:
- It would make it impossible to mark oauths emails as insecure in the future if needed (complex problem, hard to explain)
- Doesn't sound secure. More like a patch, than a feature
- Syncing such oauth login with an email&password account would be impossible.
