### ISSUE TITLE
Offline database & sync

### ISSUE THREAD

**Issue by stevenspiel** [appwrite/appwrite#346]
This looks like an awesome project. I don't see any documentation on how the database does in flutter when offline. Is there any syncing mechanism when it comes online to handle possible merge conflicts if multiple sources have edited the same data structure?

**Comment by eldadfux** [comment]
Not yet but this could be a great feature for v0.7 or 0.8.

Was thinking about adding a new query param to allow fetch of documents that were updated since a specific time date and keep paging and other filters to work the same way.

GET /v1/database/collections/[collection-id]/documents?[new-sync-param-name]=[some-date-format-unix?]

This request will return only the relevant documents, and you could still use all other query parameters to filter and sort your documents.

What do you think?

**Comment by stevenspiel** [comment]
I'm not sure how the internals would work to get an offline database. I'm assuming that a copy of the data is being stored on the device? I also don't know much about content merge strategies. Seems like being able to fetch all updates since a specific time (i.e. since the user was last connected) could work, but is that something the client should have to worry about? Or were you thinking of querying the client at the time of (re)connection to gather all the updates since last synced and send them to the server to be merged?

**Comment by TorstenDittmann** [comment]
I was doing some research in the past regarding this, how established solutions handle it.

Seems like we can learn a lot from here: 
https://github.com/amark/gun/wiki/Conflict-Resolution-with-Guns

**Comment by hbakhtiyor** [comment]
https://github.com/attic-labs/noms
https://github.com/dolthub/dolt

**Comment by luis-cruzt** [comment]
No plans on adding this? :(

**Comment by Josecodesalot** [comment]
@eldadfux  This would be an amazing addition!

**Comment by ahmedtalaltwd7** [comment]
using pouchdb with CouchDB to  sync the data by pouchdb when the app or web app is offline it stores it in the indexed or websql in the browser then when the app comes online pouchdb does fetch the data to CouchDB .
[https://pouchdb.com/](pouchdb)

[https://couchdb.apache.org/](couchdb)
