### ISSUE TITLE
🚀 Feature: Group permissions

### ISSUE THREAD

**Issue by weepy** [appwrite/appwrite#3579]
### 🔖 Feature description

* Allow users to be made members of a group without their explicit opt-in (as with teams)

### 🎤 Pitch

Say I'm creating a game where there's different levels of users who are allowed access to different resources depending on their level. 
Or say I want to grant different access levels to users - e.g. a plan (without having to invite them to join a team).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by weepy** [comment]
Ah - I found `. If initiated from server-side SDKs, the new member will automatically be added to the team.` so not really needed! 
It might be better rename Team => Group

**Comment by stnguyen90** [comment]
Thank you for raising this issue! 🙏 

All of our [APIs](https://appwrite.io/docs/client/teams) and documentations on [Permissions](https://appwrite.io/docs/permissions) refer to Teams. Is there anywher else we can make this clearer?

Is there anything else you need or can this issue be closed?

**Comment by weepy** [comment]
It would be clearer if it mentioned that you can add someone to a team
server side without the invite loop. You could also mention how Teams can
be used - as it sounds like they are only for "teams" - not groups.
(honestly Groups would be a much better term).

**Comment by stnguyen90** [comment]
Thanks for the feedback! :pray: 

> It would be clearer if it mentioned that you can add someone to a team server side without the invite loop.

Did you get a chance to read the [docs for the Create Team Membership API call](https://appwrite.io/docs/client/teams?sdk=nodejs-default#teamsCreateMembership)? If so, what can we do to make that clearer? If not, where were you looking so that maybe we can make sure to direct users to those docs?

> You could also mention how Teams can be used

Did you get a chance to read the [description](https://appwrite.io/docs/client/teams) of the Teams API? If so, what can we do to make that clearer? If not, where were you looking so that maybe we can make sure to direct users to those docs?

> as it sounds like they are only for "teams"

Can you clarify what you expected?
