### ISSUE TITLE
[Feature] Console PWA

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/appwrite#360]
Due to the rise of PWA it would be neat to add a Service Worker to the Console.

This would enable users to install the Console with a shortcut and its own window.

**Comment by PineappleIOnic** [comment]
This could be an awesome thing for me, I've been itching to learn Service Workers! 😄

**Comment by TorstenDittmann** [comment]
Even though it will be a dependency, using https://developers.google.com/web/tools/workbox might the most stress free approach.

**Comment by busseyl** [comment]
In Chrome you can do this without a Service Worker: 
![image](https://user-images.githubusercontent.com/6764970/140098668-932434f4-6c36-4046-9370-d571f48dbba2.png)

I also do this on the iPad with Safari.

The typical use case for a Service Worker is to cache assets for offline use. This doesn't appear to offer much of an advantage since the UI primarily requires a network connection to the Appwrite API services.
