### ISSUE TITLE
🐛 Bug Report: Cannot search user by phone

### ISSUE THREAD

**Issue by XanManZA** [appwrite/appwrite#3615]
### 👟 Reproduction steps

Given a user in the database has the phone number `'+123456789'`. When I try and find the user by their phone:
```javascript
const { users } = await appwriteUsersSdk.list(
    Query.equal('phone', '+123456789'),
);
console.debug(users);
```

### 👍 Expected behavior

`console.debug(users);` should return an array with 1 user Appwrite user object in it.

### 👎 Actual Behavior

`console.debug(users);` returns an empty array.

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

AWS EC2 Ubuntu 20.04

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
The [List Users](https://appwrite.io/docs/server/users?sdk=nodejs-default#usersList) API takes a search term rather than a Query. For phone based accounts, you should be able to put the phone number into the search and it should work:

https://github.com/appwrite/appwrite/blob/7ea8c3d1732e9f049d682d073e5371e39782a621/app/controllers/api/account.php#L902

Are you making any other modifications to the User after the session is created?

**Comment by XanManZA** [comment]
> The [List Users](https://appwrite.io/docs/server/users?sdk=nodejs-default#usersList) API takes a search term rather than a Query. For phone based accounts, you should be able to put the phone number into the search and it should work:
> 
> https://github.com/appwrite/appwrite/blob/7ea8c3d1732e9f049d682d073e5371e39782a621/app/controllers/api/account.php#L902
> 
> Are you making any other modifications to the User after the session is created?

Hey Steven. Just before I lodged the bug report I made doubly sure and reproduced the error - neither the `Query` nor the normal string search works.

**Comment by Meldiron** [comment]
Hey there @XanManZA 👋 Thanks for the confirmation.

I tried to create a phone session and find it using the `search` parameter, and it worked fine:

![CleanShot 2022-07-28 at 11 15 43](https://user-images.githubusercontent.com/19310830/181469381-dcdde989-6f34-4b9b-9d17-0958694fba1f.png)

> The `search` should be just a string with your phone number, including the `+` prefix.

---

I checked the source code and noticed one possible bug. Can you check if this problem is there with brand new users for you? I am suspecting that update operations are making the database lose search attribute state. For example, I can imagine the bug you are experiencing in this scenario:

- AccountAPI creates a new phone session, creating a new user
- AccountAPI changes their phone
- ServerAPI can't search with either old nor new phone number

There might be a possibly different scenario you are experiencing the bug for. Please share as much with me as possible and I will make sure to investigate it further 🙏

**Comment by XanManZA** [comment]
Hey @Meldiron sorry for taking this long to reply.
I never create a phone session. Here is our flow of data creation:
1) Create a user through the Appwrite Console
2) Add a phone for this user through the Appwrite Console
3) User the Server SDK for users to search by this phone number - no results retrieved.

Don't know if this helps?

**Comment by stnguyen90** [comment]
> Hey @Meldiron sorry for taking this long to reply. We never create a phone session. Here is our flow of data creation:
> 
> 1. Create a user through the Appwrite Console
> 2. Add a phone for this user through the Appwrite Console
> 3. User the Server SDK for users to search by this phone number - no results retrieved.
> 
> Don't know if this helps?

@XanManZA, yes, this helps! Thank you! 🙏 The Update Phone Users API doesn't make the phone number searchable because the phone number isn't verified. I'm not sure if this is the approach we want to take, though, because we make email searchable when updating email even though it's not verified. I'll talk to the team about the next steps on this.
