### ISSUE TITLE
🐛 Bug Report: Duplicate user error when using Microsoft OAuth

### ISSUE THREAD

**Issue by matfire** [appwrite/appwrite#3856]
### 👟 Reproduction steps

- create an account with an Appwrite version prior to 1.0 using an oauth provider (in my use case, microsoft)
- update Appwrite to version 1.0
- try to login using the provider used before (again, microsoft in my use case)
- A user with the same email already exists in your project.

### 👍 Expected behavior

should be able to sign in using the selected provider

### 👎 Actual Behavior

getting this error
```
Error 409
A user with the same email already exists in your project.

Error ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by matfire** [comment]
edit: this can also be reproduced using the flutter sdk on android (and possibly other platforms, I guess)

**Comment by Meldiron** [comment]
1. I spin up a Digital Ocean droplet and install 0.15.3.
2. I make a console user, create a project, and connect GitHub OAuth
3. I write a simple web app where I create OAuth user (using my GitHub account)

![CleanShot 2022-09-19 at 12 55 55](https://user-images.githubusercontent.com/19310830/191002549-e3cd36da-b2e7-4ff3-a8a4-72e5c42abbe2.png)

5. I migrate to Appwrite 1.0
6. Delete project cookies to sign out
7. Sign in again

![CleanShot 2022-09-19 at 13 03 54](https://user-images.githubusercontent.com/19310830/191003863-6c58d858-afd8-4902-8965-2fc120a735b5.png)


It worked for me 🙁 Do you have any non-Microsoft OAuth accounts? Can you confirm if this problem is there for any other provider?

**Comment by matfire** [comment]
I can try, but the problem appeared using microsoft oauth

**Comment by EVDOG4LIFE** [comment]
Closing out as this is quite old and may not be relevant. As we are quite a few versions ahead now, if this is still valid - please create a new issue with the details.
