### ISSUE TITLE
List Documents undefined behavior

### ISSUE THREAD

**Issue by delaneyj** [appwrite/appwrite#429]
[Per the documentation](https://appwrite.io/docs/client/database#listDocuments) it appears there can be undefined behavior in regards to `first` and `last` properties. 
1. Why are these integers instead of booleans?
1. What happens if you set both to true?
1. Is the first or last determined by the limit/offset used?
1. What are these properties supporting that an order+limit 1 doesn't already handle?

**Comment by eldadfux** [comment]
1. Because query strings can't really represent any types. But I guess we can cast "true" and "false" strings to boolean for better semantics with backward compatibility fallback, I'll push a PR for that.
2. When using both, no result comes back, not sure this is the best or expected result.
3. Yes. First and Last are only taken from the limit/offset range - I will add this to the docs.
4. They provide easy access to the object instead of looking for the object inside a list you can just query a single element. This does adds an extra layer of complexity, would love to get more users feedback about how useful this really is. Might consider dropping it because it will be really hard to represent this in typed systems.

**Comment by eldadfux** [comment]
Opened a PR #438 for support in "loose" boolean values in Appwrite query strings (there's a few more in the API). As long as I think about it, I guess we should deprecate both 'first' and 'last' params to be able to have a consisted response structure.
