### ISSUE TITLE
[Feature] Track File upload progress?

### ISSUE THREAD

**Issue by thereapsz** [appwrite/appwrite#440]
Is there a way to track the file upload progress when you use "storage.createFile" ?

**Comment by eldadfux** [comment]
After checking this, the Appwrite API does support XHR `progress` event for the browser (as far as I know fetch don't support this) or if you're using Flutter you can do the same using the Dio `onSendProgress` event.

Unfortunately, we don't expose a native way yet to register to this event from our SDKs yet. This is mainly because we try to keep the API method signature consisted.

A quick workaround would be to upload file directly using HTTP client and not by using Appwrite SDKs, an XHR example for this would look like this:

```javascript
let request = new XMLHttpRequest();

request.withCredentials = true;
request.open('POST', 'https://[APPWRITE-HOSTNAME]/v1/storage/files', true);

request.setRequestHeader('x-appwrite-project', 'APPWRITE-PROJECT-ID');

request.onload = function () {
    console.log(request.response); // success
};

progress = function (x) {
    console.log(((x.loaded / x.total) * 100) + '%'); // progress percentage
};

request.addEventListener('progress', progress);
request.upload.addEventListener('progress', progress, false);

let formData = new FormData();

formData.append('file', document.getElementById('test').files[0]);
formData.append('read[]', '*');
formData.append('write[]', null);

request.send(formData);
```

**Comment by thereapsz** [comment]
Thank you, this will help.
