### ISSUE TITLE
[DELETED]

### ISSUE THREAD

**Issue by muhammadirfanlive** [appwrite/appwrite#4523]
### 🔖 Feature description

[DELETED] 

### 🎤 Pitch

combability

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by muhammadirfanlive** [comment]
@eldadfux @TorstenDittmann  please read this

**Comment by eldadfux** [comment]
While criticism is encouraged and embarrassed we will not tolerate such language in the Appwrite community. Please make sure to review and follow our code of conduct and community guidelines in order to take active parts in discussions and collaborations.

https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md

**Comment by muhammadirfanlive** [comment]
@eldadfux  i want your attention at any cost sorry for that I don't want to Hurt you please. add offline combability with out offline compatibility we are not able to develop big project please. you are high level developer i am nothing please. help

**Comment by eldadfux** [comment]
Offline support is planned. This is the active community discussion about it.

**Comment by eldadfux** [comment]
https://github.com/appwrite/appwrite/issues/1168
