### ISSUE TITLE
🚀 Feature: Don't Require Index on All Attributes in Query

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4619]
> Another thing I'd like to bring up is the requirement to have an exact matching index for an API call with queries. Suppose I have an app that lists shirts and I want to let users filter by type, color, and/or size. I would need to create 6 indexes to cover all the combinations of filters they would provide. N! indexes would be annoying to create.

_Originally posted by @stnguyen90 in https://github.com/appwrite/appwrite/discussions/2720#discussioncomment-2077290_

I think having at least one partial index should be enough.

**Comment by meepeek** [comment]
Adding to @stnguyen90 point, I have a use case for accounting transaction which 11 of the attributes requires mesh indexing, it will have unique combinations of 2047 which is not feasible for the current indexes limit of 64 records.

**Comment by Loria21** [comment]
When you look up a person by their last name, it’s easy, right? You don’t have to read every page in the book. You can open to the middle page and immediately know if the name you’re searching for is earlier or later. Then open to the middle of whichever half of the book you know you should be looking in, and keep reducing the search task by half repeatedly, until you find the right page. Then on that page, you can do a similar process to find the name.

This is because the book is sorted by last name — like an index.

But suppose you need to look up a person by their first name. The book is not sorted by first name (people who have the same last name are sorted by first name, but all the people with a given first name are not together). If you need to look up a person and you only know their first name, you will have to search every page in the telephone book.

This is also just like an index in a [database](https://localpedia.io/). The index is sorted, but it’s sorted by one column at a time. The subset of entries with the same value in the first column is then sorted by the second column, then the third column, and so on.

The index doesn’t help you at all, unless your search includes the leftmost column(s) of the index.

But in a database, you may need to run a variety of queries. You could search by last name or first name or area code or the date when the person got their phone, or any number of other attributes. So you need multiple indexes, with the columns arranged in different order.

Won’t that use a lot of storage space? Yes, it will.

So you want to be efficient about how many columns you include in each index. You don’t necessarily need to duplicate all the columns in every index, only enough to help searching or sorting, and some pointer to find the master record with any other attributes.

**Comment by meepeek** [comment]
@Loria21 If I catch your point correctly. You are saying that the feature is not necessary for index should be a small set of necessary lookup and my design has a flaw that could be fixed instead of the proposed feature so the 2047 required indexes I calculated was not necessary, is that correct ?

I understand the concept you mentioned but I stuck with a real world use case while using appwrite as backend so I consulted @stnguyen90 the thing that can be done. This is the issue origin. So I would like to post more details to be considered.

I'm creating a system that collect stock data on the internet because in my country, the stock data and api are not very open and accessible so my solution is scraping web. The current backend I am using is Mongo with Typegoose. One of the collection is for keeping transactions, having these attributes (there were more, but I picked only those needed for indexing):

symbol -> stock symbol unique to a market
market -> the market the symbol being traded
type -> type of asset stock|fund|dr|fx|bond|cash
effective_date -> date which transaction occurred
settle_date -> date which transaction settled
createdAt -> for administration
updatedAt -> also for administration
action -> asset IN = deposit asset OUT = redeem
account -> the account name of a fund (this system act like a multiple funds management)
holder -> holder of asset e.g. the broker whom hold the asset or bank whom hold the cash
investor -> name of investor related to the transaction so the system can have a consensus of shares ownership

These are the 11 attributes subjected to indexing and the origin of number 2047 I mentioned. You are correct that the mesh connection between all of them might not be necessary. Most of the conventional databases just make it easy for the DB designer to just point out which of them are keys and they will handle how the indexes are made. May be appwrite traded this flexibility for efficiency and rely on manual input. I can accept that. However, it still not possible with 64 slots of index records limit that appwrite currently have. Please follow me with the calculation:

symbol, market, type <- these 3 fields must be able to query in any combination. The system will need consensus if the user want to know the very specific one or the larger picture. This is 3!
action <- also necessary on top of the first 3 to determine consensus quantity of the asset, this make it 4!
account, holder, investor <- these 3 also needed for consensus of where the total assets are and/or whom own asset and how much they own, daily. this make it 7!
effective, settle, created, updated <- all date related attributes must be added to combine with those came earlier, this will make 7!*4 (assume we place a restriction not to query multiple date related fields at once, make it harder but doable)

Now. Since we will exclude repetitions (A|B = B|A), the calculation result is: (7 + 21 + 35 + 35 + 21 + 7 + 1)*4 = 508

I need at least 508 index slots to solve the problem, even 1/4 of this is not viable in the current system limit. Also, it will not do in practical use, if the users of appwrite have to input each and every possible index combination themselves. This is just a single collection. I hope you have my point here.

What you've said is correct, we should optimize the index to be small that we will gain efficiency and speed. However, if we sacrifices all the usability for efficiency, it will only works in theory for no one able to use it. The example I provided so that the counter argument would be tangible. I think it would be pointless if I just throw an argument that the simple example you proposed just not work for me. Your argument is valid but I also have a problem at hand. Also, I appreciate both of your time spending to make this product even better.

**Comment by andrewmoore-nz** [comment]
Very keen to see some movement on this. Indexing on complex queries is becoming a massive headache, and requires some fairly cumbersome workaround for me currently.

**Comment by TorstenDittmann** [comment]
I am happy to announce that [1.3.0](https://github.com/appwrite/appwrite/releases/tag/1.3.0) is now released with less strict indexes 👏🏻 

You can find more informations in [this blog post](https://dev.to/appwrite/join-celebrations-appwrite-13-ships-relationships-57fc).
