### ISSUE TITLE
🐛 Bug Report: Register Flutter Web

### ISSUE THREAD

**Issue by GrantSavill** [appwrite/appwrite#4803]
### 👟 Reproduction steps

When I try to add a platform for Flutter Web on a fresh install, on DigitalOcean

### 👍 Expected behavior

It should add Flutter Web as a platform

### 👎 Actual Behavior

It actually pops up with an error saying invalid type

![image](https://user-images.githubusercontent.com/20668755/204581865-6f55bb31-a66d-4f34-a2b0-29dd57097f2b.png)

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by MeWasif** [comment]
hey gyz can any one plz help  me out. can I upload  DL image segmentation model deplibversion3plus  on this domain . i want to use this model in flutter mobile application, this model is in .h5 format.

**Comment by stnguyen90** [comment]
@GrantSavill, thanks for raising this issue! 🙏🏼 Would you try creating a Web platform (rather than Flutter Web) as a workaround?

**Comment by stnguyen90** [comment]
@MeWasif, sorry, I don't quite understand your request...is it related to this issue? Maybe you can join us on our [Discord](https://appwrite.io/discord/) server.

**Comment by ianmaciel** [comment]
I am facing the same issue here.
![image](https://user-images.githubusercontent.com/1381078/211570653-81a37ebc-7b3c-4269-943e-08e5765bae47.png)


I'm note sure how it should be, but it looks like the request should be only web, instead of "flutter-web":
The request are sent the with "flutter-web" platform and this error comes from the server
Request:
`{"type":"flutter-web","name":"Flutter App Write Web","hostname":"localhost"}`
![image](https://user-images.githubusercontent.com/1381078/211569133-4795f5bf-1b60-4d82-8112-0b8340fd479a.png)

Response:
`{"message":"Invalid type: Value must be one of (web, flutter-ios, flutter-android, flutter-linux, flutter-macos, flutter-windows, apple-ios, apple-macos, apple-watchos, apple-tvos, android, unity)","code":400,"type":"general_argument_invalid","version":"1.2.0"}`

If I try to create using the "web" option it works properly.

I changed the code and modified "flutter-web" for "web"  and it worked.
![image](https://user-images.githubusercontent.com/1381078/211571527-068f439f-bda3-4ae0-93f2-17480d750466.png)

**Comment by stnguyen90** [comment]
@ianmaciel, sorry, looks like we actually want to go down the route of allowing the `flutter-web` type.

**Comment by ianmaciel** [comment]
No problems! In this case, I'll close [PR #231](https://github.com/appwrite/console/pull/231).

**Comment by rombi03** [comment]
I have just faced the same issue on appwrite cloud. But it's true that the workaround works.
