### ISSUE TITLE
🐛 Bug Report: All apple sign-ins log into the same account

### ISSUE THREAD

**Issue by theniceboy** [appwrite/appwrite#4936]
### 👟 Reproduction steps

- Enable the apple provider and enter the credentials
- Sign in with `account.createOAuth2Session("apple");` (from a Flutter iOS app)
- Sign in with a different Apple ID
- Observe that AppWrite only creates one account for the two.

The account also seems to be anonymous. However, `session.provider` still says `"apple"`
![Screenshot 2022-12-31 at 12 21 42 AM](https://user-images.githubusercontent.com/8187501/210091336-2616e749-71f1-431f-aca5-c378fe61d62a.png)

### 👍 Expected behavior

- The user id of an apple sign in should be unique

### 👎 Actual Behavior

When signing in with any apple id, AppWrite returns the same user.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

- Flutter 3.3.0, appwrite Flutter SDK 8.1.0
- iPadOS 16
- AppWrite self-hosted

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@theniceboy thanks for raising this issue. 🙏🏼 

It seems odd that the identifier is blank for your user. I tested, and the identifier shows up with my email if I select share email or a private relay email address if I select hide email. 

Could you try logging out and signing in with apple again?

**Comment by theniceboy** [comment]
Hi @stnguyen90 thank you for your response!

For me, I didn't get the options to choose to share my email or do private email, which is odd. I did include the "email" scope but that didn't help.
Unfortunately, I was on a tight schedule to implement auth, so I had to use something else. This issue might have been caused by some mistake I made. I can leave this open if you'd like to investigate. Feel free to close it anytime.

**Comment by stnguyen90** [comment]
@theniceboy, ya you should see something like:

![image](https://user-images.githubusercontent.com/1477010/211087895-a2267dce-64f9-444e-a930-740a60128e5b.png)

I didn't change any scopes for my flutter code:

```dart
await widget.account.createOAuth2Session(
  provider: 'apple',
  success: 'http://localhost:57942/auth.html',
);
```

You might want to:

1. reset your apple id sign in:
   1. Sign in to your Apple ID: https://appleid.apple.com/sign-in
   2. Click on Sign in with Apple
   3. Click on your app
   4. Click Stop using Sign in with Apple
2. Log out of your flutter app
3. Delete the user in the Appwrite Console
4. Try signing in with Apple again

If you need a resource on setting up Sign in with Apple, check out https://dev.to/appwrite/apple-sign-in-with-appwrite-2576.

I don't think there's any other troubleshooting I can do so I'm going to close this for now. Feel free to comment and I can re-open in the future.

**Comment by jonafeucht** [comment]
FYI: I faced a similar issue, so here is how I fixed it. Hope it helps whoever stumbles onto this issue.

If you've deleted the user and then signed in again, it is likely that you will create an anonymous user. This occurs because Apple does not resend the name and email during this process, because from Apple's perspective, the user is still logged in.

To work around this problem, you can follow these steps:
1. Go to your account management page: [https://appleid.apple.com/account/manage](https://appleid.apple.com/account/manage).
2. Click on "Sign In with Apple" to access the list of apps and websites associated with your Apple ID.
3. Locate your app/website and remove it from the list.

By removing the app/website from the list, you should be able to address the problem.
