### ISSUE TITLE
🐛 Bug Report: Error Creating Project

### ISSUE THREAD

**Issue by wallace7souza** [appwrite/appwrite#4941]
### 👟 Reproduction steps

Hi guys! I ran appwrite 1.2.0 and for some reason, I can't create any project over an organization 

### 👍 Expected behavior

The console send this:
{"projectId":"unique()","name":"dc-site-cms","teamId":"6329b95392a9a75b1ed9","region":"default"}

And I received this:
{"message":"Server Error","code":500,"type":"general_unknown","version":"1.2.0"}

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/3328434/210236274-ea71e06c-b3f3-4288-b691-69f171b4d06b.png)

How can I debug this?
Or there is a method to completely remove it and restart it?
I ran the docker command to install 1.2.0, there was a previous appwrite version.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I'm using Docker version 20.10.12, build 20.10.12-0ubuntu4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@wallace7souza thanks for creating this issue! 🙏🏼 

> How can I debug this?

Would you please check the docker logs for the appwrite container to see the details on the 500 error?

> Or there is a method to completely remove it and restart it?

Since Appwrite uses docker volumes to persist the data, to remove Appwrite completely, you would need to wipe the volumes. You can follow [this](https://appwrite.io/docs/installation#uninstall) to remove all containers and volumes.

> I ran the docker command to install 1.2.0, there was a previous appwrite version.

You can only have 1 instance of appwrite on a server. Typically, people upgrade their instances following the [upgrade docs](https://appwrite.io/docs/upgrade).

**Comment by wallace7souza** [comment]
Thanks for replying @stnguyen90 !!

I found this on logs

[Error] URL: /v1/projects
[Error] Type: Utopia\Database\Exception\Structure
[Error] Message: Invalid document structure: Unknown attribute: "region"
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Database.php
[Error] Line: 1364

Maybe is some conflict  with the previous appwrite version, I'll try remove all and install  again.
I found

**Comment by stnguyen90** [comment]
@wallace7souza, ya I've seen this before when people upgraded to the latest version of Appwrite without running the migrate command. 

Can this be closed now?
