### ISSUE TITLE
Cannot create document with reference to parent

### ISSUE THREAD

**Issue by tomwyr** [appwrite/appwrite#498]
I tried to set up simple database structure with albums and songs where each album document stores an array of songs (and few more properties). When I try to create new song with a reference to an album with this code:

```Dart
await _database.createDocument(
  collectionId: '5f2c2f2b664d3',
  data: {
    'name': 'song_2',
    'length': 32,
  },
  read: ['*'],
  write: ['*'],
  parentDocument: '5f2c3d2f49eec',
  parentProperty: 'songs',
  parentPropertyType: 'append',
);
```

I receive following error in the response:

```
{
  message: Bad structure. Invalid document structure: Unknown property "length" type. Make sure to follow albums collection structure, 
  code: 400, 
  version: 0.6.2
}
```

However, when I comment out *parentDocument*, *parentProperty* and *parentPropertyType* params, api call is successful and new song gets created.

**Comment by tomwyr** [comment]
I am using Appwrite package in a Flutter project.

**Comment by eldadfux** [comment]
@tomwyr this feature is actually about to be deprecated in the next Appwrite version (0.7). You can just create the same data structure by nesting the song document inside the album document like this:

```
await _database.createDocument(
  collectionId: 'album_collection_id_here',
  data: {
    'name': 'song_2',
    'songs': [
    {
       '$collection': 'songs_collection_id_here',
       'name': 'song_1',
       'length': 32,
     },
     {
        '$collection': 'songs_collection_id_here',
        'name': 'song_2',
        'length': 32,
      },
    ]
  },
  read: ['*'],
  write: ['*'],
);
```

**Comment by tomwyr** [comment]
Thanks for the clarification.
Is it possible (or is it planned) to create new document and link it with its parent but after the parent was created (so basically adding new song to an existing album in my case)?

**Comment by eldadfux** [comment]
I was thinking of creating a specific route for it instead of the current way which adds a lot of complexity (and parameters).

This are a few options:

1. `PATCH /v1/database/document/:parent/:property` which accept parameters: `value`, `type` (assign, append, prepend)
2. `POST /v1/database/document/:parent/relationship` which accept parameters: `property`, `childId`, `type` (assign, append, prepend)

Would love to get your thoughts on this.

**Comment by tomwyr** [comment]
Both approaches seem to work well, as long as it's possible to add/remove a relation between two documents. When opting the second option, I would expect to be able to call DELETE with relevant `property` and `childId` in order to get rid of that connection and, in case of the first one, maybe an additional param like `action` (add/remove) could be enough?

Another approach that comes to my mind is to be able to call different routes for each of the parent document properties. E.g.
- `POST /v1/database/document/albums/{id}/songs` creates new song in `songs` collection and adds it to `songs` array in album
- `PUT /v1/database/document/albums/{id}/songs/{id}` adds existing song reference to `songs` array in album
- `DELETE /v1/database/document/albums/{id}/songs/{id}` removes song reference from `songs` array in album

I am not sure, though, if it's technically possible to implement it in this way. I used this SO answer as a reference: https://stackoverflow.com/a/6328012/5954950.

**Comment by punitdiwan** [comment]
I always want to have JSON field in documents itself. I have seen it in many NoSQL solutions like Strapi, Parse etc. Since, JSON fields are challenge for GraphQL, I think @eldadfux your 2nd option `POST /v1/database/document/:parent/relationship which accept parameters: property, childId, type (assign, append, prepend)` is better.

One thing I would like to ask, is it possible to insert JSON field in a document as string using only REST API but we can fetch that field in GraphQL as String. What I mean, if its problematic to create GraphQL Mutation with JSON fields, we can stick with REST API for insertion but for GraphQL Query, we can fetch JSON field as string as show it as response.

@eldadfux  What do you say?

Regard,
Punit

**Comment by eldadfux** [comment]
@punitdiwan I had a similar idea, where the response for GraphQL will be different for us to support hashmaps in the REST API. My initials thought was to have a list of objects with key and value attributes that might allow easier out-fo-the-box parsing for GraphQL users than a JSON string. The downside for this is that it will not be fully suitable for JSON, only for <string>:<string> hashmaps what do you think?

**Comment by punitdiwan** [comment]
@eldadfux  Hash map is by all means one step forward to Array. It allows tostore greater level of structured content in single collection. Can we store Object as a value part in map and also fetch in GraphQL. If it does we can represent the data like this. Hay @tomwyr , I am using your sample  as its very simple to explain, he he.

`//Simple Object
 songList = [{
    'name' : 'song1',
    'singer': 'X Singer',
    'length'; '3min',
},
{
    'name' : 'song2',
    'singer': 'Y Singer',
    'length'; '4min',
},
]

// albums is a map
albums = map();
albums.add('Album1', SsongListong)
`
If there is problem in saving values like this, we can encode into base64 the value before saving and decode it back after fetching. We can modify SDK to do this.
@eldadfux what do you say?

**Comment by eldadfux** [comment]
Modifying the SDKs like that might be a bit tricky, as we auto-generate them in almost 10 different langs now. I would like to test your JSON as a string idea as part of the GraphQL branch, would be very interesting to see how it works with some real use-cases,
