### ISSUE TITLE
[HELP-WANTED] Adding Support for More OAuth Providers

### ISSUE THREAD

**Issue by mixty1** [appwrite/appwrite#5]
Is it possible to add my own auth provider, for example, I need to add vk.com or maybe this feature will be added later?

**Comment by eldadfux** [comment]
Hi @mixty1, currently have only 3 working OAuth providers working (facebook, github and linkedin).

I am working right now to simplify the process of adding new providers and I am going to write a detailed tutorial explaining how to add new providers to our source code.

This is an area where I really hope  the community will give a hand, as we need to support as many **major** OAuth providers as possible.

**Comment by eldadfux** [comment]
OK, I have added a short tutorial that explains the steps required to add a new OAuth provider to the project.

Still need to change some things regarding the way we add new provider logos, but should be enough to get started.

The tutorial is here:
https://github.com/appwrite/appwrite/blob/master/docs/AddOAuthProvider.md

And should followed after reading our new contribution guide:
https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md

And the code of conduct:
https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md

Let me know if there is any feedback!

**Comment by christyjacob4** [comment]
Hey guys I would like to work on this. Please let me know if I can! Cheers!

**Comment by eldadfux** [comment]
Hey @christyjacob4, sure you can. That will be amazing.

Before forking, please let us know here which providers you want to add first.

Also, make sure to read the [contribution guide](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md) to follow our standards and best practices.

If anything is not clear please let me know. You can also join our Gitter community for live support and discussions:
https://gitter.im/appwrite/community

Happy #hacktobefest!

**Comment by christyjacob4** [comment]
Hey @eldadfux  Thanks for the prompt reply. I would like to start with Google and as I get familiar with the process would like to add more providers like Gitlab etc.. If you have any suggestions please let me know. 

I'll approach you in case something is not clear. 
Cheers!

**Comment by eldadfux** [comment]
@christyjacob4 Google & Gitlab sounds great! I am available for any question!

**Comment by valishah** [comment]
Hey @eldadfux: Is it fine if I grab github oAuth and work?

**Comment by eldadfux** [comment]
Hey @valishah, actually we already have implementations of Facebook, *Github* and Linkedin ready and working and @christyjacob4 is working on now on Google and Gitlab integrations.

But you can just tell me if there is any other provider you would like to work on and I will make a list to help future contributors know what integrations are still missing or in work.

**Comment by rhyseli** [comment]
Hey! I'd like to add support for Twitter

**Comment by eldadfux** [comment]
Hey @rhyseli,

Currently, @christyjacob4 has added Google & Gitlab adapters and is working on these adapters:

* Bitbucket
* Instagram
* Microsoft
* Twitter

@christyjacob4 maybe you could use some help with the new adapters?

@christyjacob4 Also note that according to these docs (https://developer.twitter.com/en/docs/basics/authentication/api-reference/token) Twitter has added support for OAuth 2, so this should be a lot less complicated than we thought.

@rhyseli If you would like, we could also use adapters for:
* Yahoo
* Apple - [Should be very similar to OAuth 2 ](https://developer.apple.com/sign-in-with-apple/resources/)
* Amazon
* Discord
* Twitch
* Dropbox
* Mail.ru
* Reddit
* Slack

**Comment by rhyseli** [comment]
Okay no problem. Shall I have a go with discord and twitch then?

**Comment by Orozco93** [comment]
Can I help with the Slack support?

**Comment by donofriov** [comment]
I'll add Twitch support.

**Comment by christyjacob4** [comment]
Hey everyone as @eldadfux has mentioned These are the remaining providers we wish to implement as of now with more suggestions welcome
[ ] Yahoo
[ ] Apple - Should be very similar to OAuth 2
[ ] Amazon 
[ ] Discord
[ ] Twitch
[ ] Dropbox
[ ] Mail.ru
[ ] Reddit
[ ] Slack
A fellow developer has implemented twitter, so Im waiting for it to be merged
[ ] Twitter
[x] Bitbucket
[x] Facebook
[x] Github
[x] Gitlab
[x] Google
Instagram has some technical difficulties since their API doesn't return an email ID, which we require.x
[ ] Instagram 
[x] Microsoft
[x] Linkedin

Currently I'll be working on Reddit, Dropbox and Apple

Others are welcome to choose what ever is remaining and also suggest new providers. 

@donofriov Please check your abstract class Implementations since some of them are missing. Conduct tests to ensure that the user is being added as shown. 
![test1](https://user-images.githubusercontent.com/20852629/66026596-ca71af00-e516-11e9-9e00-70da807cfcdf.png)
Ensure that the providers name is present in the payload. 

@Orozco93 Sure you can start working on it..

If you guys need any help please reach out on gitter

**Comment by christyjacob4** [comment]
Hey everyone as @eldadfux has mentioned These are the remaining providers we wish to implement as of now with more suggestions welcome
- [ ] Yahoo
- [ ] Apple - Should be very similar to OAuth 2
- [ ] Amazon 
- [ ] Discord
- [ ] Twitch
- [ ] Dropbox
- [ ] Mail.ru
- [ ] Reddit
- [ ] Slack
A fellow developer has implemented twitter, so Im waiting for it to be merged
- [ ] Twitter
- [x] Bitbucket
- [x] Facebook
- [x] Github
- [x] Gitlab
- [x] Google
Instagram has some technical difficulties since their API doesn't return an email ID, which we require.x
- [ ] Instagram 
- [x] Microsoft
- [x] Linkedin

Currently I'll be working on Reddit, Dropbox, Apple and Amazon

Others are welcome to choose what ever is remaining and also suggest new providers. 

@donofriov Please check your abstract class Implementations since some of them are missing. Conduct tests to ensure that the user is being added as shown. 
![test1](https://user-images.githubusercontent.com/20852629/66026596-ca71af00-e516-11e9-9e00-70da807cfcdf.png)
Ensure that the providers name is present in the payload. 

@Orozco93 Sure you can start working on it..

If you guys need any help please reach out on gitter

**Comment by christyjacob4** [comment]
Hey everyone as @eldadfux has mentioned These are the remaining providers we wish to implement as of now with more suggestions welcome
- [ ] Yahoo
- [ ] Apple - Should be very similar to OAuth 2
- [ ] Amazon 
- [ ] Discord
- [ ] Twitch
- [ ] Dropbox
- [ ] Mail.ru
- [ ] Reddit
- [ ] Slack
A fellow developer has implemented twitter, so Im waiting for it to be merged
- [ ] Twitter
- [x] Bitbucket
- [x] Facebook
- [x] Github
- [x] Gitlab
- [x] Google
Instagram has some technical difficulties since their API doesn't return an email ID, which we require.x
- [ ] Instagram 
- [x] Microsoft
- [x] Linkedin

Currently I'll be working on Reddit, Dropbox, Apple and Amazon

Others are welcome to choose what ever is remaining and also suggest new providers.  

@donofriov Please check your abstract class Implementations since some of them are missing. Conduct tests to ensure that the user is being added as shown. 
![test2](https://user-images.githubusercontent.com/20852629/66027124-e0cc3a80-e517-11e9-8b0f-86a2a7f6e235.png)

Ensure that the providers name is present in the payload. 

@Orozco93 Sure you can start working on it..

If you guys need any help please reach out on gitter

**Comment by BogDAAAMN** [comment]
@eldadfux @christyjacob4 I've got Slack. Just a quick fix and I'll make the PR

**Comment by christyjacob4** [comment]
@BogDAAAMN  That's great .. Kindly post a screenshot in your PR so we can verify it.
You can follow this comment 
https://github.com/appwrite/appwrite/pull/93#issuecomment-537458845

**Comment by pratikhmehta** [comment]
Hey! I'd like to add support for Instagram.

**Comment by eldadfux** [comment]
Hey @pratikhmehta,

Instagram adapter is currently on hold due to some technical difficulties. 😞

**Comment by christyjacob4** [comment]
@rhyseli  Are you still working on discord? Please let us know.

**Comment by rhyseli** [comment]
Hi @christyjacob4, yes I'm still working on Discord. Should get my PR in this weekend.

**Comment by rhyseli** [comment]
> Hi @christyjacob4, yes I'm still working on Discord. Should get my PR in this weekend.

I'm having some trouble with the docker container, namely that the mariadb container is timing out and refusing connections which is stopping me from testing. Could delay me a bit on the discord integration.

**Comment by Naamboon** [comment]
It gonna be works

**Comment by eldadfux** [comment]
@mixty1 , Notice that #135 added the VK OAuth provider which actually started this issue 🥳.

**Comment by nilmanichandrakar** [comment]
suggestion for a provider- stack exchange

**Comment by christyjacob4** [comment]
@nilmanichandrakar  it'll be done tonight

**Comment by nilmanichandrakar** [comment]
I'm already working on this

**Comment by christyjacob4** [comment]
@nilmanichandrakar  I don't think It would work now since their api doesnt return the user's email ID

**Comment by Kolkies** [comment]
Any updates about the discord provider? Otherwise I can look into it

**Comment by eldadfux** [comment]
@christyjacob4 do you remember whats the Discord adapter status?

**Comment by christyjacob4** [comment]
@eldadfux  The last update on Discord was here https://github.com/appwrite/appwrite/issues/5#issuecomment-539483624

@rhyseli Do we have any updates on Discord OAuth ? Let us know if you would like to continue working on it.

**Comment by PineappleIOnic** [comment]
Hey there, Is anyone working on the apple adapter?

**Comment by eldadfux** [comment]
@PineappleIOnic, @christyjacob4 has started to work on it, but we got stuck when we were trying to create a demo app with test credentials from Apple. Will be great if you could help us.

**Comment by PineappleIOnic** [comment]
@eldadfux alright, once I get my docker back up and working I'll get right to work trying to add it

**Comment by manaswinidas** [comment]
Any OAuth providers still left to be integrated? I'd like to extend a helping hand too :smile:

**Comment by eldadfux** [comment]
Hey @manaswinidas , we could use some help with Discord and Twitch for a start.

**Comment by manaswinidas** [comment]
@eldadfux I saw that a PR has already been created for Twitch. I'm doing for Discord

**Comment by eldadfux** [comment]
@manaswinidas that's great. I think the Twitch PR has been abandoned as it isn't active for more than a month.

**Comment by Naamboon** [comment]
I Hope get a new version

**Comment by armino-dev** [comment]
Hi @eldadfux, I can help with adding more providers. 
I have tried to play around with Github OAuth to see how it's working, but it seems something is broken.
I get a _Missing Project UID_ error.
I used this link pattern to test:
http://localhost/v1/auth/login/oauth/callback/github/{project_id}?success=http://localhost/?success=1&failure=http://localhost/auth/signin?failure=2
I noticed also on appwrite.io/console I get the same error when trying to login using one of the OAuth provider.
Am I doing something wrong?

**Comment by christyjacob4** [comment]
> Hi @eldadfux, I can help with adding more providers.
> I have tried to play around with Github OAuth to see how it's working, but it seems something is broken.
> I get a _Missing Project UID_ error.
> I used this link pattern to test:
> [http://localhost/v1/auth/login/oauth/callback/github/{project_id}?success=http://localhost/?success=1&failure=http://localhost/auth/signin?failure=2](http://localhost/v1/auth/login/oauth/callback/github/%7Bproject_id%7D?success=http://localhost/?success=1&failure=http://localhost/auth/signin?failure=2)
> I noticed also on appwrite.io/console I get the same error when trying to login using one of the OAuth provider.
> Am I doing something wrong?

@armino-dev can you share the steps you followed?

**Comment by armino-dev** [comment]
> > Hi @eldadfux, I can help with adding more providers.
> > I have tried to play around with Github OAuth to see how it's working, but it seems something is broken.
> > I get a _Missing Project UID_ error.
> > I used this link pattern to test:
> > [http://localhost/v1/auth/login/oauth/callback/github/{project_id}?success=http://localhost/?success=1&failure=http://localhost/auth/signin?failure=2](http://localhost/v1/auth/login/oauth/callback/github/%7Bproject_id%7D?success=http://localhost/?success=1&failure=http://localhost/auth/signin?failure=2)
> > I noticed also on appwrite.io/console I get the same error when trying to login using one of the OAuth provider.
> > Am I doing something wrong?
> 
> @armino-dev can you share the steps you followed?

@christyjacob4 
Here are the steps:

1. I created a sample project
2. I created an OAuth app on Github and got the client id and secret
3. I navigated to Users > Providers, inserted the data from Github and save it.
4. I tried http://localhost/v1/auth/login/oauth/callback/github/{project_id}?success=http://localhost/?success=1&failure=http://localhost/auth/signin?failure=2 with my project id off course.

**Comment by christyjacob4** [comment]
This is the endpoint you need to hit
http://localhost/v1/auth/login/oauth/github?project={project_id}&success=http://localhost/?success=1&failure=http://localhost/auth/signin?failure=2

**Comment by armino-dev** [comment]
oops, thanks

**Comment by christyjacob4** [comment]
@armino-dev I hope it works now

**Comment by eldadfux** [comment]
@christyjacob4 I think @armino-dev is hitting the same bug we had when we were working on the #261 issue.

@armino-dev i'll push a fix into the master to fix the missing project UID error. This is caused due to our lack of e2e testing for OAuth providers.

In this issue #275 i'll make sure to add a mock OAuth server that will be tested in the CI server and make sure this kind of thing don't happen again.

**Comment by armino-dev** [comment]
Yes @eldadfux, you are correct. I have just tried with the correct endpoint and I get the same missing project UID error.

**Comment by eldadfux** [comment]
Just committed a fix to the master branch:
https://github.com/appwrite/appwrite/commit/c5444c828ffa6938be4e0f9901fb2f7a970e9aeb

If you are building the Appwrite container from the master branch and not from version 0.4.0 on Docker Hub you should just sync your master and I think this should work for you.

**Comment by armino-dev** [comment]
I have just synced my fork, and everything it's working smoothly. I can make the Discord and Twitch OAuth integration for start, or any other provider you suggest.
Let me know if it's ok, and thanks for the fix.

**Comment by christyjacob4** [comment]
@eldadfux I think Discord and Twitch would be great as well.
You can refer to this comment https://github.com/appwrite/appwrite/issues/5#issuecomment-537380277 to get more information on providers we have planned.

Feel free to suggest more providers as well.

**Comment by armino-dev** [comment]
Ok, thanks. I'll come with a PR soon.

**Comment by eldadfux** [comment]
Updated @christyjacob4 list:

**Done:**
- [x] BitBucket
- [x] Facebook
- [x] Github
- [x] GitLab
- [x] Google
- [x] Microsoft
- [x] LinkedIn
- [x] Slack
- [x] DropBox
- [x] Amazon
- [x] VK
- [x] Discord
- [x] Twitch
- [x] Spotify

Ready for new PRs:
- [ ] Twitter (OAuth2 not OAuth1)
- [ ] SoundCloud
- [ ] Apple (Should be very similar to Auth2 - requires Apple developer account)
- [ ] Yahoo
- [ ] AOL
- [ ] Stripe
- [ ] Shopify
- [ ] PayPal
- [ ] Mail.ru
- [ ] Yandex
- [ ] Baidu
- [ ] Renren
- [ ] Weibo

**On Hold:**
* Instagram (Instagram has some technical difficulties since their API doesn't return an email ID, which we require)
*  Reddit (Reddit has some technical difficulties since their API doesn't return an email ID or a UUID or a full name, which we require)

**Comment by eldadfux** [comment]
Just updated the the list with our latest Bitly and Salesforce adapters.
I thinks that if we have no technical issues with Twitter we should prioritise it.

**Comment by armino-dev** [comment]
I have played yesterday with more providers, for example, battle.net and Vimeo. They do not return emails, unfortunately.
I think Shopify can't be used because their API is tight to a store. You need to make requests to an endpoint like {shop}.myshopify.com/admin/api
I tried Stripe but can't verify my account. Romania is not in their countries list, so I have abandoned it.
I'll play with Twitter API today and see if it can be fitted to our abstraction class

**Comment by eldadfux** [comment]
@armino-dev thanks for the update.

As mentioned before on Discord and to keep everyone here at sync, Appwrite requires the email as a unique id for login and account recovery. We do have plans to add phone support and allow anonymous login in the future. Once we are there, I think we can revisit all the adapters that don't return an email.

We should also make future plans for custom settings, to allow adapters like Shopify and to allow more flexibility for adapters like PayPal, who support a production and a sandbox envs.

**Comment by eldadfux** [comment]
Just finished working on the Apple adapter 🤘

**Comment by eldadfux** [comment]
Closed in favor of #410
