### ISSUE TITLE
🐛 Bug Report: States are not getting reseted in Create Attribute Modal

### ISSUE THREAD

**Issue by yatharth1706** [appwrite/appwrite#5133]
### 👟 Reproduction steps

Open Create Attribute modal and select any data type. Enter any values and close the modal.

Next time when user comes to create attribute modal, states are not reseted.

Example video:

https://user-images.githubusercontent.com/32243289/219410436-2027dcf2-5a70-401d-bc14-f3704289122d.mp4

### 👍 Expected behavior

States of all input should get reset

### 👎 Actual Behavior

States are not getting reset

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by yatharth1706** [comment]
Hy @stnguyen90 I want to work on this issue. Can you assign it to me ?

**Comment by stnguyen90** [comment]
@yatharth1706, thanks for creating this issue! 🙏🏼 Perhaps this is happening because we are only [clearing the option](https://github.com/appwrite/console/blob/ca08b538c90b088551a7c0a2c3403b6514c1a94a/src/routes/console/project-%5Bproject%5D/databases/database-%5Bdatabase%5D/collection-%5Bcollection%5D/createAttribute.svelte#L56), but not the actual [data](https://github.com/appwrite/console/blob/ca08b538c90b088551a7c0a2c3403b6514c1a94a/src/routes/console/project-%5Bproject%5D/databases/database-%5Bdatabase%5D/collection-%5Bcollection%5D/createAttribute.svelte#L17-L21).

**Comment by yatharth1706** [comment]
Hey @stnguyen90 are you working on it ? I was thinking to contribute to this. Its fine if you are working on it
