### ISSUE TITLE
🚀 Feature: Ability to provide a custom URL scheme to createVerification method

### ISSUE THREAD

**Issue by gidrokolbaska** [appwrite/appwrite#5134]
### 🔖 Feature description

Hello, guys!
In the current API for email confirmation (createConfirmation method) we have to provide a URL which basically forces us to make a static webpage which handles the email confirmation.
So for example, when I send an email with a confirmation link, it looks like this: http://localhost/?userId=blablabla
How my mobile app should handle this link? Right, we can't handle this link without either
a. Having a static webpage which will handle this for us;
b. Hosting a proper website on a trusted domain with an assetlinks.json file (which also requires a lot of setup for both android and ios).
Why I just can't provide myawesomeapp://verify to the URL parameter? This way, we will receive the following link in the email: myawesomeapp://verify/?userId=blablabla which can actually be handled by our app (if proper modifications are made to AndroidManifest or Info.plist). this will bring us directly to our app where we can handle this deep link and parse the required parameters in order to complete verification.

So, in short, currently you are forcing us to use App Links (Android) and Universal Links (iOS) which:
* **Android**
   work with https scheme and require a specified host, plus a hosted file - assetlinks.json
* **iOS**
   only work with https scheme and require a specified host, entitlements and a hosted file - apple-app-site-association

So that forces us to make a website with those files which I've mentioned above

And it would be much simpler if we could use Deep Links (Android) and Custom URL schemes (iOS) instead.

### 🎤 Pitch

Nothing to add here, all the information is in the above section.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@gidrokolbaska, thanks for opening this issue! 🙏🏼 

> In the current API for email confirmation (createConfirmation method) we have to provide a URL which basically forces us to make a static webpage which handles the email confirmation.

I think it's best to put an HTTPS URL rather than use a custom URL scheme because:

1. You can still set up deep links so that an HTTPS URL will direct the user into an app
2. Sometimes, email apps won't open custom URL schemes
3. Ideally, you would have a page hosted as a fallback incase the user opens the URL on a device that doesn't have the app

When using custom URL schemes, what happens if you try to set `myawesomeapp://localhost/verify` or `myawesomeapp://[your appwrite hostname]/verify` as the URL? If you want to use `myawesomeapp://verify`, could you try adding a web platform with the hostname of `verify`?

**Comment by stnguyen90** [comment]
@gidrokolbaska, is there anything else you need or can this be closed?

**Comment by gidrokolbaska** [comment]
> @gidrokolbaska, is there anything else you need or can this be closed?

I've switched to firebase, closing the issue
