### ISSUE TITLE
📚 Documentation: Add code snippets about how to add permissions and attributes along with creating collections 

### ISSUE THREAD

**Issue by VenkataBhaskarr** [appwrite/appwrite#5183]
### 💭 Description

According to the discussion happened in discord it is cleared that we could add permission and attributes along with creating collections in the code itself rather than in the dashboard manually for each and every collection but it would be more appreciated if docs contains the code snippet examples of how to perform the above tasks.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Danish-Belal** [comment]
### Adding Permissions
User can add permissions to his collection by specifying the read and write permissions for the collection. 
Here's how to do it:

`const appwrite = require('appwrite');

const client = new appwrite.Client();
client.setEndpoint('https://[HOSTNAME_OR_IP]/v1');
client.setProject('[PROJECT_ID]');
client.setKey('[API_KEY]');

const collection = await client.collections.create('myCollection', ['*'], ['*']);
`
In the above code, we create a collection called myCollection and specify ['*'] for both read and write permissions, which grants access to all users.

Dear @VenkataBhaskarr  can you assign me this issue so that i can make documentation .
