### ISSUE TITLE
🐛 Bug Report: Use of Insecure Random Number Generator

### ISSUE THREAD

**Issue by superiorsd10** [appwrite/appwrite#5236]
### 👟 Reproduction steps

Inside the `src/Appwrite/Auth/OAuth2/Etsy.php`, `rand` is used for the random number generation process to create the URL. But it's unsafe, and vulnerable to attack. So instead of using this static random number generator, we can use CSPRNG (Cryptographically secure pseudorandom number generator) functions. 

### 👍 Expected behavior

PHP provides `random_int` to generate cryptographically secure integers. So instead of using `rand` we can use `random_int` to generate random integers. 

### 👎 Actual Behavior

![SCR-20230316-fv7](https://user-images.githubusercontent.com/92971894/225527639-0f23ac4b-cefe-45b5-895e-24bc82df8e49.png)

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by superiorsd10** [comment]
Can you please assign this issue to me?

**Comment by stnguyen90** [comment]
@superiorsd10, thanks for raising this issue! Let me check some things and get back to you.

**Comment by stnguyen90** [comment]
@superiorsd10, so after looking into this a bit more, I don't think we need to make sure the int is cryptographically secure because [`random_bytes()`](https://www.php.net/manual/en/function.random-bytes.php) is what actually makes the cryptographically secure value. The `rand()` is only used so that we have a random size for the cryptographically secure value.
