### ISSUE TITLE
🐛 Bug Report: Document creation doesn't accept `False` for a boolean attribute's value

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/appwrite#5389]
### 👟 Reproduction steps

When I create a document from the console, a boolean attribute's value is not accepted if it is `false`. It works if set to `true`.
Since it can be a `required` field, I have to first set the value to `true` & then update it to `false`.

### 👍 Expected behavior

Accept the `false` value 👀.

### 👎 Actual Behavior

Shows an error: `This field is required`.

See attached screenshot for reference.

![image](https://user-images.githubusercontent.com/20625965/232410315-b3246727-9a72-4a3a-bf18-6f6e2facf0dd.png)

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Localhost.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by aabmets** [comment]
I have also encountered this issue. I'm not entirely certain, but this should be an easy fix. I'm assuming that currently the "required" status of a field is currently being checked by the server by whether a "truthy" value exists for the field. It should be changed so that it checks if the key exists in the data object that is passed to the server in the request. If a field is required, then the key must exist in the dictionary, irrespective of the value that it points to.

**Comment by aabmets** [comment]
That PR fix works also :P
