### ISSUE TITLE
🐛 Bug Report: Appwrite Oauth2 facebook provider not working :(

### ISSUE THREAD

**Issue by polataydinn** [appwrite/appwrite#5413]
### 👟 Reproduction steps

When i try to integrate facebook authentication to my appwrite server, i cannot use this feature. It says that the provider is disabled which is already enabled and integrated with the keys which are taken from facebook.

![image](https://user-images.githubusercontent.com/45331624/233320912-0294a351-f0c3-4d0f-b92b-2648ed148541.png)

![image](https://user-images.githubusercontent.com/45331624/233321407-305f2c60-fbc1-4bcf-81ff-595cedca32a6.png)

### 👍 Expected behavior

It should authenticate to facebook when i use this feature

### 👎 Actual Behavior

Throws an error that says i should enable facebook provider :(

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@polataydinn, thanks for raising this issue! 🙏🏼 This seems to be working fine for me. Please make sure you're using the correct project ID and provider in your client app. Maybe you can share the network log from your browser for the create oauth2 session API call. If you do, please make sure to share the request headers.

By the way, it might be easier to troubleshoot this on [Discord](https://appwrite.io/discord) rather than GitHub.

**Comment by stnguyen90** [comment]
@polataydinn, are you still having issues with this? FYI, I'll need to close this soon due to inactivity.

**Comment by polataydinn** [comment]
Thanks for your support, i installed appwrite through digital ocean image so i figured out that that image version is old.

After updating appwrite to the latest version everything works fine now.
