### ISSUE TITLE
🐛 Bug Report: Create File Modal Is Cut Off

### ISSUE THREAD

**Issue by NielsKrijnen** [appwrite/appwrite#5420]
### 👟 Reproduction steps

When trying to add a file to a bucket, the UI isn't right.
![image](https://user-images.githubusercontent.com/92881475/233790905-e2fbae3b-ff8d-4942-b68d-fb444259072c.png)

### 👍 Expected behavior

The UI shows up as normal

### 👎 Actual Behavior

The UI looks weird

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Appwrite Version: 1.3.1
SDK: Svelte

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi - seems like this could be specific to some browsers or window sizes because when I tried to reproduce this, I get this:
<img width="577" alt="Screenshot 2023-04-22 at 9 55 00 PM" src="https://user-images.githubusercontent.com/72690202/233795790-342b57bd-d9ba-445a-bdd8-1e9ef50d05b8.png">

I am going to pass this to my team and let you know further.
