### ISSUE TITLE
:rocket: Feature: Console custom URL path

### ISSUE THREAD

**Issue by aabmets** [appwrite/appwrite#5430]
Add the ability to change the default console URL path in the config file.
This would enable one to hide the consoles login page, which would protect it 
from brute force login attacks.

There are plugins that do this for WordPress for example, which hide the default 
/wp-admin login path and substitute it with whatever string the user has provided.

**Comment by stnguyen90** [comment]
@aabmets, thanks for raising this issue! 🙏🏼 FYI, this is a little difficult right now because:

1. the [Console uses file-based routing](https://github.com/appwrite/console/tree/main/src/routes) and expects the paths to be a certain way. The Console is also statically built, so changing the path at runtime wouldn't be possible.
2. the backend routes various paths to the Console frontend:

https://github.com/appwrite/appwrite/blob/e311b6bd0e7f5d801756aac88091260613b6529c/app/controllers/web/console.php#L6-L19

**Comment by aabmets** [comment]
@stnguyen90 
File based routing is not an issue, because Svelte has parameterized file routes.
You could implement it like: 
src/pages/[randstr]/+console.js
And put a logic check into the console.js file which checks if the randstr param matches the one defined in the configuration. Hell, there is no need for even for doing it through the appwrite config file, bc the console itself could store the obfuscated route value into whatever db it maintains its own state in.

**Comment by eldadfux** [comment]
This issue seems to not get much attention from the community and the effort to make this possible will be too big vs the benefits. Our official recommendation for hosting Appwrite with other apps on the same domain is to separate it but using a different subdomain.
