### ISSUE TITLE
🐛 Bug Report: Server Error when trying to create Document on Appwrite Cloud

### ISSUE THREAD

**Issue by semroig** [appwrite/appwrite#5691]
### 👟 Reproduction steps

Go to a collection and try to create a document.

### 👍 Expected behavior

Create Document.

### 👎 Actual Behavior

Server Error pop up, impossible to create Document...
<img width="1440" alt="Screen Shot 2023-06-12 at 10 58 51" src="https://github.com/appwrite/appwrite/assets/63104910/6b474668-74ad-444f-9195-5420c389a3d5">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

I use Google Chrome.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by evergreenx** [comment]
i am experiencing the same error .

**Comment by joeyouss** [comment]
Hi
Most probably this has been fixed now, can you please try once again and let me know here?

**Comment by joeyouss** [comment]
We would like to inform you that one of our databases is currently undergoing an upgrade due to the growing number of cloud users. As a result, projects utilizing this database will temporarily operate in read-only mode. This means that a subset of users may experience limitations in performing write operations during this period. We anticipate that the upgrade will be completed within the next few hours, after which all functionality will be fully restored.

We sincerely apologize for any inconvenience this may cause and appreciate your understanding during this upgrade process.

**Comment by Mahmoudgalalz** [comment]
> @joeyouss Any updates on hackathon extension? Since the server isn't working right now.

I'm with this to extend the hackathon as a lot of things got broken and testing and validating anything is hard to do

so at least one day extend will be good to finish our projects

**Comment by scshiv29-dev** [comment]
any update @joeyouss  ? the outage still continues

**Comment by Haimantika** [comment]
> @joeyouss Any updates on hackathon extension? Since the server isn't working right now.

The hackathon deadline has been extended by a day to 15th June

**Comment by Haimantika** [comment]
> any update @joeyouss ? the outage still continues

Are you still facing the issue?

**Comment by Haimantika** [comment]
@semroig like @joeyouss mentioned, there was an outage that caused this error. Let me know if it fine now, and we can proceed to close this issue

**Comment by semroig** [comment]
It looks like Appwrite Cloud Database and Auth services are working fine now. I'll close this issue, thanks @Haimantika and @joeyouss !! 🤙
