### ISSUE TITLE
🐛 Bug Report: Event session.delete not trigger when remove cause of TTL

### ISSUE THREAD

**Issue by fliitor** [appwrite/appwrite#5801]
### 👟 Reproduction steps

1. Set Session length to 5 seconds (or what you need to test)
2. Add a debug function (wich just listen all `users.*.sessions.*` events, and output on `res.json`
3. Create a session (via email in my case)
4. Check that session is removed (`account/sessions/[SESSION_ID]` endpoint)
5. Check logs of function on 2.

No event is triggered

### 👍 Expected behavior

Event aboute deletion of session need to be populate (on function / webhooks)

### 👎 Actual Behavior

No log about this event

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Ubuntu 22.04 & Docker compose

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@fliitor, thanks for creating this issue! 🙏🏼 Unfortunately, the event is not triggered automatically when a session expires. It is only triggered when a user [deletes their session](https://appwrite.io/docs/client/account?sdk=web-default#accountDeleteSession). Part of the reason is the session is not actually deleted. Instead, the browser automatically removes it client-side because of the expiration on the session cookie, or Appwrite ignores the session because it [doesn't pass verification](https://github.com/appwrite/appwrite/blob/73329ad21979265532b3d2d561dacfa53052b0b2/app/init.php#L862).

**Comment by stnguyen90** [comment]
@fliitor, we do already have a maintenance task:

https://github.com/appwrite/appwrite/blob/73329ad21979265532b3d2d561dacfa53052b0b2/app/tasks/maintenance.php#L97-L102

that triggers the delete expired sessions job:

https://github.com/appwrite/appwrite/blob/73329ad21979265532b3d2d561dacfa53052b0b2/app/workers/deletes.php#L419-L435

However, these don't trigger the event because the event is only triggered when the user logs out via the API.

**Comment by fliitor** [comment]
I can close it, mb
