### ISSUE TITLE
Smooth scroll feature is missing

### ISSUE THREAD

**Issue by rishipurwar1** [appwrite/appwrite#585]
When we press the scroll to top button, it suddenly goes to the up. So, I want to add a smooth scroll feature to it.

![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/57035408/94770750-0ca42980-03d3-11eb-8ea1-658a7f3ed094.gif)

**Comment by rishipurwar1** [comment]
I would like to add to work on this...

**Comment by iarmankhan** [comment]
I can take this up if nobody is working on it.

**Comment by rishipurwar1** [comment]
@iarmankhan  I am working on it

**Comment by eldadfux** [comment]
@rishipurwar1 please not that appwrite.io is still not open-source. The code for this component does sit on this repo: https://github.com/appwrite/appwrite/blob/d05a8479b9bbc61c8d42ca2942fde8bf58c750d4/public/scripts/views/general/scroll-to.js#L5

You would probably need to tweak the Appwrite dashboard to make sure any changes are working because this button is hidden in the console of this repo.

**Comment by Gajesh2007** [comment]
I am working on it

**Comment by rishipurwar1** [comment]
Go for it @Gajesh2007

**Comment by Gajesh2007** [comment]
Where is index.html?

**Comment by Gajesh2007** [comment]
@eldadfux Where is index.html?

**Comment by eldadfux** [comment]
There is no index.html. What exactly are you trying to achieve?

**Comment by Gajesh2007** [comment]
@eldadfux I wanted to add a Smooth scroll feature

**Comment by eldadfux** [comment]
@Gajesh2007 Please review our [Contribution Guide](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md) for more info about Appwrite design and architecture. If you still need help, please reach out on the #maintainers channel on our Discord server. https://appwrite.io/discord.
