### ISSUE TITLE
🐛 Bug Report: Unable to delete file from storage

### ISSUE THREAD

**Issue by RehanGG** [appwrite/appwrite#6163]
### 👟 Reproduction steps

- Tried to delete the file using Flutter SDK
- Used deleteFile function

### 👍 Expected behavior

It should delete file

### 👎 Actual Behavior

It fails to delete the file and shows this error,

![image](https://github.com/appwrite/appwrite/assets/35191555/227b0323-df24-4225-bdb9-f2acf8d5d127)

and in appwrite container logs, it display this error,

![image](https://github.com/appwrite/appwrite/assets/35191555/e6992712-d08b-433c-b9cb-b253707632f5)

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Using Flutter SDK of appwrite (10.0.1)
Appwrite 1.4.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhinav700** [comment]
@RehanGG I would love to work on this issue. Can you please assign this to me.

**Comment by stnguyen90** [comment]
@RehanGG, thanks for creating this issue! 🙏🏼 Unfortunately, that file is now in an invalid state because the actual file is gone, but the file container/metadata/document is still there. This is the same issue as https://github.com/appwrite/appwrite/issues/6042 and will be fixed in 1.4.2 to prevent this invalid state from happening again.

For now, would you be able to recreate the collection? That should delete the file metadata.

**Comment by learnwithalex** [comment]
i want to work on this
