### ISSUE TITLE
🐛 Bug Report: Can't set function event to trigger Webhook

### ISSUE THREAD

**Issue by byawitz** [appwrite/appwrite#6218]
### 👟 Reproduction steps

When trying to create a Webhook that will be triggered by any function-relate events you get the following error.
```
Invalid `events` param: Value must a valid array 
and Triggering a function on a function event is not allowed."
```
![image](https://github.com/appwrite/appwrite/assets/316103/2e186965-063d-4ef7-9b27-0b7ff03358d9)

The payload that was sent in the test
```json
{
  "name": "Test",
  "events": [
    "functions.*.executions.*"
  ],
  "url": "https://test.com/test",
  "security": false
}
```

### 👍 Expected behavior

Appwrite should create a function-based triggered webhook.

### 👎 Actual Behavior

Appwrite blocks any function-based event creation, as seen [here](https://github.com/appwrite/appwrite/blob/master/src/Appwrite/Event/Validator/Event.php#L50) for all available triggers, function and webhooks and should block [only](https://discord.com/channels/564160730845151244/1150634893882175528/1150910514118008843) functions.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@byawitz, thanks for creating this issue! 🙏🏼 This validation was added to protect Appwrite from a function triggering a function in an infinite recursive loop. The problem is the same validator is used for Webhooks. Let me talk to the team about how to proceed.

**Comment by stnguyen90** [comment]
So, instead of using the same [Event Validator](https://github.com/appwrite/appwrite/blob/5717fbe28243a7616434d908554db51d28c4f35d/src/Appwrite/Event/Validator/Event.php) for both, we should have one that doesn't have this check:

https://github.com/appwrite/appwrite/blob/5717fbe28243a7616434d908554db51d28c4f35d/src/Appwrite/Event/Validator/Event.php#L49-L52

And then have a FunctionEvent Validator that's a subclass of the Event Validator that also checks for the `functions.` and blocks it.

**Comment by byawitz** [comment]
Can you assign it to me?

**Comment by stnguyen90** [comment]
@byawitz assigned! Thanks for your interest! 🙏🏼
