### ISSUE TITLE
🐛 Bug Report: Cloud - Appwrite after using "github" as sign in, delete project.

### ISSUE THREAD

**Issue by juandl** [appwrite/appwrite#6239]
### 👟 Reproduction steps

I am using Cloud Appwrite and signed up using my GitHub account. After creating a project, I attempted to delete it, but I was prompted to enter a password that I didn't have.

### 👍 Expected behavior

Not sure what should be the expect behaviour...

### 👎 Actual Behavior

![image](https://github.com/appwrite/appwrite/assets/25650720/c364cef8-a3e4-4c6d-b425-2097a3fd8d23)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@juandl, thanks for raising this issue! 🙏🏼 This has been fixed in a newer version, but Cloud is pending upgrade. For now, you'll need to set a password using the "Forgot Password?" on the sign in page:

<img width="645" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/9820977a-a23e-4340-8578-1373a5cba975">

Then, you can fill out the form to delete the project.

**Comment by eldadfux** [comment]
Password is no longer required for this.
