### ISSUE TITLE
🚀 Feature: Stack support should be introduced for Docker Swarm and Kubernetes

### ISSUE THREAD

**Issue by tuvaergun** [appwrite/appwrite#6359]
### 🔖 Feature description

There are many differences in Docker Swarm and Kubernetes installations and it is not possible to run them directly. I think it is important to make it easier to use and offer a more scalable structure.

### 🎤 Pitch

Stack support should be introduced for Docker Swarm and Kubernetes

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
We recommend scaling using docker swarm because Appwrite functions uses the Docker CLI to spin up containers and won't work on K8s. You can refer to the following community resources for help with this:

* https://book.appread.io/docker-swarm
*  https://dev.to/hackmamba/how-to-create-a-docker-swarm-of-appwrite-containers-and-ui-with-swarmpit-1nje

For K8s, you can 👍🏼 the following issues:

* https://github.com/appwrite/appwrite/issues/24
* https://github.com/appwrite/appwrite/issues/364
