### ISSUE TITLE
🚀 Feature: Improve UX with Custom Scrollbar on Website.

### ISSUE THREAD

**Issue by letscodedanish** [appwrite/appwrite#6882]
### 🔖 Feature description

The website currently uses the default scrollbar, which can be enhanced for a better user experience.
This feature will eventually improve the UX of the website. 

### 🎤 Pitch

Requesting the implementation of a custom scrollbar in a visually appealing color to elevate the website's aesthetics.
According to my preference, the color #e34c7a would suit well with the website's design.

![Screenshot (509)](https://github.com/appwrite/appwrite/assets/112203113/5ab61a84-0dfb-47cc-883d-f23e88b15279)
 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

I want to work on it,please assign it to me.

**Comment by ddevilz** [comment]
please assign this issue to me

**Comment by parthsolanki1498** [comment]
willing to work on this, please assign if possible. Thank you

**Comment by letscodedanish** [comment]
I already worked on it, will make a PR today.

**Comment by kmr-sahil** [comment]
I want to work on this issue please assign this to me !!

**Comment by kmr-sahil** [comment]
not totally agree with you but, this default scroll bar is breaking the design consistency or brand consistency when any user visits website and come across this ! different browsers have different default scroll bars, focusing on these small changes will led to perfection in design.
Also having a dark theme website and default grey scrollbar is still distracting visitors. 

btw I am also aspiring UI developer

**Comment by TGlide** [comment]
@kmr-sahil thanks for your passion in discussing this subject! I have a few thoughts to share to explain our reasoning.

> this default scroll bar is breaking the design consistency or brand consistency when any user visits website and come across this

This is a browser element rather than a page element, it's not inconsistent. Even big brands with heavy focus on design don't usually change the scrollbar. Same as they don't change the cursor very often! It's also notoriously hard to style a scrollbar consistently across browsers.

> Also having a dark theme website and default grey scrollbar is still distracting visitors.

It's quite the opposite. Our accent colour is meant to be used sparingly, to draw attention to it. If you put the accent colour on a scrollbar, each time you scroll you'll be drawing attention to it, when it's meant to be a subtle indicator and control related to page navigation, not something to be highlighted.

A grey colour, however, is very muted, and closer to the darker tones of the website, meaning it doesn't stand out as much, which is quite desirable. Sometimes less is more!

**Comment by kmr-sahil** [comment]
Thank you @TGlide  for your detailed and informative explanation. As a student, I am still learning, and I was previously unaware that "Even big brands with heavy focus on design don't usually change the scrollbar". I also appreciated your explanation of the accent color, which draws attention to the scrollbar.

I apologize for any inconvenience I may have caused you or anyone else. However, grateful for this conversation that I have learned something new.

**Comment by Haimantika** [comment]
> Thank you @TGlide for your detailed and informative explanation. As a student, I am still learning, and I was previously unaware that "Even big brands with heavy focus on design don't usually change the scrollbar". I also appreciated your explanation of the accent color, which draws attention to the scrollbar.
> 
> I apologize for any inconvenience I may have caused you or anyone else. However, grateful for this conversation that I have learned something new.

Hi @kmr-sahil please do not apologize, we are thankful that you asked us and that we could have this conversion. :) Will be closing this issue for now. Would also invite you to join our community on [Discord](https://appwrite.io/discord), hoping we can learn from each other!
