### ISSUE TITLE
🐛 Bug Report: How to search full collection

### ISSUE THREAD

**Issue by SMARTMICROWORLD** [appwrite/appwrite#6892]
### 👟 Reproduction steps

How to search full collection if i have multiple attribute index like this??

![ss](https://github.com/appwrite/appwrite/assets/25653690/9dc83fff-7606-4e10-a35e-f79d11212d64)

### 👍 Expected behavior

I want to get results from all column that is selected in index.

### 👎 Actual Behavior

But I am getting:
AppwriteException: Invalid query: Attribute not found in schema: text,category,main_category
AppwriteException: Invalid query: Attribute not found in schema: text,category,main_category

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

I am using Appwrite cloud on react native

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by SMARTMICROWORLD** [comment]
The code:
appwriteDatabases
      .listDocuments(DATABASE_ID, CONTENTS_COLLECTION_ID, [
        Query.search('text,category,main_category', 'anim'),
      ])
      .then(data => console.log(data));

**Comment by stnguyen90** [comment]
@SMARTMICROWORLD, thanks for creating this issue! 🙏🏼 The search query (just like any other filter query such as `Query.equal()` only works on 1 attribute. So you would do `Query.search('text' 'anim')`. 

If I understand you correctly, the logic you're looking for is like:

```
Query.search('text' 'anim') OR Query.search('category' 'anim') OR Query.search('main_category' 'anim')
```

This type of query is not supported yet. I suggest you 👍🏼 the [related issue](https://github.com/appwrite/appwrite/issues/2740) to express your interest and stay updated on the feature request.

For now, I would suggest either:

1. Make 3 full text indexes (1 for each attribute) and make 3 separate API calls searching on each attribute
2. Create a `search` attribute that has data from all 3 attributes and create 1 full text index on that attribute

For now, I'm going to close this issue since we already have https://github.com/appwrite/appwrite/issues/2740.

**Comment by SMARTMICROWORLD** [comment]
> @SMARTMICROWORLD, thanks for creating this issue! 🙏🏼 The search query (just like any other filter query such as `Query.equal()` only works on 1 attribute. So you would do `Query.search('text' 'anim')`.
> 
> If I understand you correctly, the logic you're looking for is like:
> 
> ```
> Query.search('text' 'anim') OR Query.search('category' 'anim') OR Query.search('main_category' 'anim')
> ```
> 
> This type of query is not supported yet. I suggest you 👍🏼 the [related issue](https://github.com/appwrite/appwrite/issues/2740) to express your interest and stay updated on the feature request.
> 
> For now, I would suggest either:
> 
> 1. Make 3 full text indexes (1 for each attribute) and make 3 separate API calls searching on each attribute
> 2. Create a `search` attribute that has data from all 3 attributes and create 1 full text index on that attribute
> 
> For now, I'm going to close this issue since we already have #2740.

Thanks for this help but these are temporary solutions I want advanced search like elastic or algol... in appwrite

**Comment by vinay-sd17** [comment]
> ```
> Query.search('text' 'anim') OR Query.search('category' 'anim') OR Query.search('main_category' 'anim')
> ```

Hi, If I want to search for a single full-text field - with an OR condition inside the search, like below query 

Query.search("fullTextCol", ["node", "next"]). Is it allowed?
