### ISSUE TITLE
🐛 Bug Report: Related VCS documents aren't deleted when a function is deleted

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#7018]
### 👟 Reproduction steps

1. Create a project
2. Connect to GitHub
3. Deploy a function using GitHub integration
4. Create a PR on the function repo to create VCS comments
5. Delete the function

### 👍 Expected behavior

All related documents such as:

- installations
- repositories
- vcsComments

### 👎 Actual Behavior

These may not be deleted

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by vermakhushboo** [comment]
Hey @stnguyen90, just reproduced the issue. Here is what is currently happening when we delete the function:
1. `installations` collection still has the installation details: `expected` since deleting function shouldn't affect installation
2. `repositories` collection still has the repository details: `unexpected` since repo is no longer linked to the Appwrite function
3. `vcsComments` collection still has the comment details: `unexpected` since repo details should be deleted from collections
4. `functions` collection doesn't have data: `expected` since function has now been deleted

I'm now debugging the `unexpected` behaviours and will be raising a PR.
