### ISSUE TITLE
📚 Documentation: Realtime/Subscribe docs confusing

### ISSUE THREAD

**Issue by R0N1n-dev** [appwrite/appwrite#7050]
### 💭 Description

Not sure about the realtime/subscription docs.
Subscribe works as described here
```js
import { Client } from "appwrite";

const client = new Client()
    .setEndpoint('https://cloud.appwrite.io/v1')
    .setProject('[PROJECT_ID]');

client.subscribe('account', response => {
    // Callback will be executed on all account events.
    console.log(response);
});
```
Then docs talk about unsubscribe so as not to lead to race conditions
```js
import { Client } from "appwrite";

const client = new Client()
    .setEndpoint('https://cloud.appwrite.io/v1')
    .setProject('[PROJECT_ID]');

const unsubscribe = client.subscribe('files', response => {
    // Callback will be executed on changes for all files.
    console.log(response);
});

// Closes the subscription.
unsubscribe();

```
If i use subscribe as the first one, it works, but it leaves it subscribed if i am not mistaken, hence the need for unsubscribe, but if i use the unsubscribe , i never get my callback.
How do i use subscribe and unsubscribe as well properly coz am confused according to the docs and the results in my app?????

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Utkarshn10** [comment]
Hey @R0N1n-dev the docs suggest to use `subscribe` if you are not duplicating your subscriptions. So I think you can use subscribe as per your usecase.

This is what docs suggests:
`If you no longer want to receive updates from a subscription, you can unsubscribe so that your callbacks are no longer called. Leaving old subscriptions alive and resubscribing can result in duplicate subscriptions and cause race conditions.`

**Comment by R0N1n-dev** [comment]
Ok.Thanx
