### ISSUE TITLE
📚 Documentation: How to query a datetime attribute?

### ISSUE THREAD

**Issue by carlodenardin** [appwrite/appwrite#7290]
### 💭 Description

I posted the problem on [stack](https://stackoverflow.com/questions/77665907/appwrite-unable-to-query-by-date-with-dart) and since there are other users with this issues I think a documentation should be provided.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
In my opinion, Flutter does `toIso8601String()` a little weird in that the timezone stays in the local timezone. Best practice when working with a remote server is to send data to the server in UTC timezone. So, instead of:

```dart
date.toIso8601String()
```

do

```dart
date.toUtc().toIso8601String()
```

when you create the document or query.

Also, be careful with doing an exact match (`Query.equal()`) on date times because if the millisecond doesn't match up, the query won't match.

FYI, the best place to get help is in the support channel on our [Discord](https://appwrite.io/discord) server.

**Comment by stnguyen90** [comment]
Related Discord thread: https://discord.com/channels/564160730845151244/1185336790945644595

**Comment by stnguyen90** [comment]
As mentioned on Discord, the suggestion above worked out so I'll close this issue now.
