### ISSUE TITLE
🐛 Bug Report: Replacing existing collection attribute with one of the same name does not automatically grab the same data

### ISSUE THREAD

**Issue by dennislbc** [appwrite/appwrite#7357]
### 👟 Reproduction steps

1. Create collection
2. Set attributes (example: description, length 300)
3. Add items that use this attribute.
4. Delete this attribute and recreate it.

### 👍 Expected behavior

Items should contain the data previously set for the same attribute. 

### 👎 Actual Behavior

Not all items previously created will hold the data correctly. Some items when viewing them will show null for this attribute, others will show the previous description.

To fix the issue, the user must go into each item and scroll down to the description, change at least 1 character and press update. When the user is inside of the specific item, they will see the previously set data for that attribute, but the server sees it as 'null'. So the user must change and update the value to get it past the null. 

This issue could be avoided if we could change the length of a previously set attribute. 

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@dennislbc, thanks for creating this issue! 🙏🏼 Yes, it is expected that deleting an attribute will delete the data.

If you're looking for a way to update an attribute, you might want to add a 👍🏼 to this issue: https://github.com/appwrite/appwrite/issues/6287.

I'm going to close this issue since Appwrite is behaving as expected and we have another issue for updating attributes already.
