### ISSUE TITLE
🐛 Bug Report: 404 when fetching bucket files

### ISSUE THREAD

**Issue by Vivek-Shaw** [appwrite/appwrite#7398]
### 👟 Reproduction steps

i found the issue that appwrite throws "Storage bucket with the requested ID could not be found." for existing Buckets.

so at first it was working fine but suddenly I am getting 500 internal server error 
https://cloud.appwrite.io/v1/storage/buckets/6569f6f890aa545197bd/files
so I created a new bucket and getting same error for that one too.
https://cloud.appwrite.io/v1/storage/buckets/6597ec48748787d74ebd/files
But on the appwrite dashboard both the buckets are showing 
![Screenshot 2024-01-05 173713](https://github.com/appwrite/appwrite/assets/47256717/539e1fd1-255a-4355-967e-249d444a2c59)
![Screenshot 2024-01-05 173805](https://github.com/appwrite/appwrite/assets/47256717/1fc4e39a-48fa-4c9f-a4c7-215200444c5c)
![image](https://github.com/appwrite/appwrite/assets/47256717/ab63209a-be3d-47d8-a22e-41df4442dd97)

### 👍 Expected behavior

all buckets should work

### 👎 Actual Behavior

no bucket is working.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

0.12.32

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Vivek-Shaw, thanks for creating this issue! 🙏🏼 This is the expected behavior when you enter `https://cloud.appwrite.io/v1/storage/buckets/6597ec48748787d74ebd/files` in the URL of your browser because:

1. Appwrite doesn't know what project you're trying to fetch the files for
2. you're not authenticated as an end user 

The best thing to do would be to use one of our [SDKs](https://appwrite.io/docs/sdks), [CLI](https://appwrite.io/docs/tooling/command-line/installation), or [REST API](https://appwrite.io/docs/apis/rest) to access the bucket.
