### ISSUE TITLE
🐛 Bug Report: Insecure mount of /var/run/docker.sock

### ISSUE THREAD

**Issue by diego-treitos** [appwrite/appwrite#7423]
### 👟 Reproduction steps

The proposed `docker-compose.yml` mounts `/var/run/docker.sock` with write permissions in 2 instances. This is a huge security risk. Is this really necessary? Traefik should only need readonly and I am not sure about the other one.

Even using `:ro` when mounting is a big security flaw, but nothing near full write permissions.

### 👍 Expected behavior

At least mount `/var/run/docker.sock` in read-only mode.

### 👎 Actual Behavior

In the proposed `docker-compose.yml` 2 different containers mount `/var/run/docker.sock` with write permissions so if any of those containers is compromised, the host and all other containers will be compromised.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@diego-treitos, thanks for raising this issue! 🙏🏼 

For traefik and docker, you can refer to the [Traefik docs](https://doc.traefik.io/traefik/providers/docker/#docker-api-access). Following the suggestions by Traefik can be a good approach to harden your deployment.

The openruntimes-executor container does require access to the docker socket so that it can create containers at runtime for Appwrite functions. If you don't need to use Appwrite Functions, you can disable the container.
