### ISSUE TITLE
🐛 Bug Report:  The Account API is being called from the login page and is failing.

### ISSUE THREAD

**Issue by ksidht** [appwrite/appwrite#7476]
### 👟 Reproduction steps

First, I observed this issue in local setup in http://localhost/login. when i rechecked with server in https://cloud.appwrite.io/login page, same issue found 

### 👍 Expected behavior

Account api must not called in login page.

### 👎 Actual Behavior

Added screenshots from local & live versions
<img width="1552" alt="Screenshot 2024-01-21 at 12 37 55 AM" src="https://github.com/appwrite/appwrite/assets/20462672/06351180-d2d9-4964-b1c6-ab5258029e73">
<img width="1552" alt="Screenshot 2024-01-21 at 12 38 05 AM" src="https://github.com/appwrite/appwrite/assets/20462672/f2f5069b-1a89-4f3e-9d66-fd2f12831740">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
@docimin you're almost 100% correct, just that we can read the secure cookie from the client side. Making a call to the account is a common way to verify the user state when an application load. If we see the user is logged we will redirect them to the app instead of showing the login/signup screens.
