### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Rahulwagh228** [appwrite/appwrite#7642]
### 👟 Reproduction steps

when i try to connect my frontend with the backend this cors issue is occuring, i've tried everything but it isn't working anymore

### 👍 Expected behavior

i thought after the signup the request would create a new user account but it got rejected by the cors
![Screenshot 2024-02-23 195414](https://github.com/appwrite/appwrite/assets/127666835/6dc5be2a-ebf4-4de9-a1d4-412fdb221495)

### 👎 Actual Behavior

i've got the cors error... 

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

1.4.13

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by cbum-dev** [comment]
Can you provide your source code ?

**Comment by EVDOG4LIFE** [comment]
@Rahulwagh228 - these issues are typically caused by misconfigurations and not an actual issue with the code. We've created a video guide [here](https://www.youtube.com/watch?v=oEpRh9H5l5g) that walks through the most common CORS errors our developers experience. 

I encourage you to post your inquiry on our [Discord](https://appwrite.io/discord) to continue this conversation with the community. This would be the best approach in for this case!

Thanks!

**Comment by Rahulwagh228** [comment]
https://github.com/Rahulwagh228/Swiftsnap

This is the code and I'm new in web development... I was just trying to
make project using youtube...

https://www.youtube.com/watch?v=_W3R2VwRyF4&list=PL6QREj8te1P6wX9m5KnicnDVEucbOPsqR

This is the youtube link... Please help me with that...
