### ISSUE TITLE
🐛 Bug Report: Rest API request to List Documents returns 400 (Bad Request) if X-Appwrite-Response-Format is not set

### ISSUE THREAD

**Issue by feschaffa** [appwrite/appwrite#7774]
### 👟 Reproduction steps

I recently updated to Appwrite 1.5.1. I have a browser extension that needs to use the fetch API on Chrome (I'm not able to use the web SDK there). Until Appwrite 1.4.13, I could make requests to the REST API by setting just the X-Appwrite-Project header. After the update, the extension broke, always returning error 400 (Bad Request) when using the "List Documents" endpoint, with no error message.

After some tinkering and analyzing how the official SDK made the requests, I got it to work by setting the X-Appwrite-Response-Format to "1.4.0". However, that header is marked as "optional" in the documentation. 
If this is now required, I suggest pointing that out in the documentation.

Thank you! Nice update, by the way 😉

### 👍 Expected behavior

As per the documentation, the only required headers for Rest API are "X-Appwrite-Project" and "Content-Type".

### 👎 Actual Behavior

Error 400 (Bad Request) with no error message when not including the "X-Appwrite-Response-Format" header.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.5.1
Fetch API (chrome extension)
Rest API

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@feschaffa, thanks for creating this issue! 🙏🏼 I tried to reproduce your error, but it worked fine for me:

<img width="772" alt="image" src="https://github.com/appwrite/appwrite/assets/1477010/b2587768-9c59-46c6-b92c-d281d378519a">

Would you please share the request you made? Perhaps you passed a query in the 1.4 format which is why it returned 400.

**Comment by feschaffa** [comment]
Sure! Here you go:

![Error400](https://github.com/appwrite/appwrite/assets/35773180/bf8b1a75-b523-4d16-93ea-006952cd0119)

I didn't know the query format changed 🤔

Thank you!

**Comment by stnguyen90** [comment]
@feschaffa, yes, it's actually JSON now to support nesting and make parsing easier. We still need to update the REST API docs (cc @gewenyu99). However, if you add the response format header and set it to 1.4.0, your old queries should still work. That's why the response format header is important.

Maybe [this](https://github.com/appwrite/sdk-for-web/blob/e907a873fa53452e4c746ac8afbfb3ee07637958/src/query.ts#L29-L33) will give you an idea what the new format is.

**Comment by feschaffa** [comment]
Ooh, I see, great!

I'll use the response format header for now and wait until the docs are up-to-date then.

Thank you for your time looking into this, @stnguyen90 !
