### ISSUE TITLE
🐛 Bug Report: Error 500 on Auth/Databases/Functions/Storage tabs

### ISSUE THREAD

**Issue by bkkoluch** [appwrite/appwrite#7788]
### 👟 Reproduction steps

1) Enter any tab mentioned in the title

### 👍 Expected behavior

Page is displayed correctly, no error is shown.

### 👎 Actual Behavior

Page is not displayed correctly, error 500 is shown.

![image](https://github.com/appwrite/appwrite/assets/58911502/0dfb3f52-48c4-465d-8dc3-d7c0e3b21322)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@bkkoluch, thanks for raising this issue! 🙏🏼 This was probably due to the incident that occurred. For the latest information on the status of Appwrite Cloud, check https://status.appwrite.online/. You can also subscribe to get notifications about incidents on that status page.

Are you still experiencing this problem? If so, what's your project ID?

**Comment by bkkoluch** [comment]
@stnguyen90 thank you for the response!

Everything I've mentioned is already working, you can close the issue 👍.
