### ISSUE TITLE
🐛 Bug Report: 500 Internal Server Error

### ISSUE THREAD

**Issue by AmitSutradhar001** [appwrite/appwrite#7796]
### 👟 Reproduction steps

Authentication and Database everywhere I'm getting this. Even in my account. 

### 👍 Expected behavior

 500 Internal Server Error

### 👎 Actual Behavior

 500 Internal Server Error

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@AmitSutradhar001, thanks for raising this issue! 🙏🏼 If you were experiencing this on Appwrite Cloud, it's probably due to the incident that occurred. For the latest information on the status of Appwrite Cloud, check https://status.appwrite.online/. You can also subscribe to get notifications about incidents on that status page.

Are you still experiencing this problem? If so, what's your project ID?
