### ISSUE TITLE
Issues with nested documents in array properties on documents

### ISSUE THREAD

**Issue by didair** [appwrite/appwrite#785]
## 🐛 Bug Report

Im trying to add a 'product' to a 'list' in array 'list.products (product type)'
'product' contains an array with nested documents called 'prices'
If i send the entire 'product' object i get this error:
message    "Bad structure. Invalid document structure: Property "products" has invalid input. Invalid document structure: Property "prices" has invalid input. Invalid document structure: Collection not found"
code    400
version    "0.6.2"

## Have you spent some time to check if this issue has been raised before?
Had a conversation in Discord about the issue.

## To Reproduce
Create two document types, and nest one of them to another in an array. Create a third that nests the "parent" document in an array and try adding that to the third doucment in a list.

## Expected behavior
If i remove the "prices" array from the "product" i want to add to my "list", the prices also gets removed from the "product" itself. This seems to be an unexpected behavior. If i PATCH collections/lists/documents/listID I expect only that document to be updated, not the nested documents.

**Comment by eldadfux** [comment]
Updating that we solved the issue itself. Seems like on of the nested collection had a missing read attribute for the user to access it.

**Comment by eldadfux** [comment]
Leaving this issue open to rethink the patch endpoint behavior.

**Comment by damascenaluiz** [comment]
I have a similar scenario problem A collection called 'Form' -> array of 'Questions' (Document) -> array of alternatives (Text),

It turns out that in the UI I cannot add the alternatives directly when creating a form, the ADD button does not let me add the alternatives, but the other options in the Question I can modify normally.

If I go directly to the Questions collection, I can insert the alternatives, but they appear empty in the Form collection.

Appwrite 0.7.0

**Comment by TorstenDittmann** [comment]
Closing this in favor of #1063
