### ISSUE TITLE
🚀 Enhancement: Support deploy K8S

### ISSUE THREAD

**Issue by nguyenthanhtien** [appwrite/appwrite#7891]
### 🔖 Enhancement description

I want using appwrite deploy to K8S, appwrite can support?

### 🎤 Pitch

For scale system high demand.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@nguyenthanhtien, thanks for creating this issue! 🙏🏼 Appwrite does not work on K8s yet due to functions being reliant on docker and the docker socket. We suggest scaling vertically or horizontally with docker swarm. That said, others in the community have gotten Appwrite running on K8s (For example, there's [this](https://discord.com/channels/564160730845151244/1127927989548626031/1127933450163322902) thread about [Microtica](https://github.com/microtica/templates/tree/master/appwrite/.microtica)).

Otherwise, we do already have 2 open issues related to K8s:

* https://github.com/appwrite/appwrite/issues/24
* https://github.com/appwrite/appwrite/issues/364

As such, it would be good to add a 👍🏼 to those as I'm going to close this as a duplicate.
