### ISSUE TITLE
🐛 Bug Report: Remove button on stuck attributes

### ISSUE THREAD

**Issue by tripolskypetr** [appwrite/appwrite#7920]
### 👟 Reproduction steps

On appwrite 1.3 we can fix attribute creation stuck by pressing remove button and recreating attribute few times

### 👍 Expected behavior

That was like "fix appwrite button" , so the collection was useable. With extra attribute, it unusable

### 👎 Actual Behavior

Right now, instead of fixing problem, appwrite designer team simple mindless hide the remove button on the stucked attribute so we can't punch appwrite in the ui without risks of accessing docker directly

![image](https://github.com/appwrite/appwrite/assets/19227776/631725e2-35ee-4974-a165-5200a290e1f7)

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Self hosted 1.5.4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@tripolskypetr, thanks for creating this issue! 🙏🏼 This was done because, most of the time, attributes were legitimately processing and developers would try to delete them, ending up with stuck attributes. We plan to improve the experience with stuck attributes as part of https://github.com/appwrite/appwrite/issues/7432 and may bring back the button in the Console if it makes sense.
