### ISSUE TITLE
🚀 Enhancement: Add new option to API keys

### ISSUE THREAD

**Issue by TechComet** [appwrite/appwrite#7986]
### 🔖 Enhancement description

Add new option to API keys

add "One Time" to Expiration Date

### 🎤 Pitch

I need a one-time API to complete the installation process of the application provided to the client

![Screenshot from 2024-04-17 17-40-39](https://github.com/appwrite/appwrite/assets/5288136/52567144-48a7-420e-846f-2e8e2c12e3ce)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by avezqureshi14** [comment]
I want to work on this issue, can u please assigned this to me

**Comment by stnguyen90** [comment]
@TechComet, thanks for creating this issue! 🙏🏼 

> I need a one-time API to complete the installation process of the application provided to the client

Doing something like that with an API key sounds risky because an API key gives significant privileges. I would do something like this by having a collection of codes and exposing access via an Appwrite Function. The function would validate the code, mark it as used, and then do whatever needs to be done.

**Comment by TechComet** [comment]
I use it only at website one time

**Comment by eldadfux** [comment]
A workaround for this would just to use the api key from a function and if the operation you needed was already performed throw an error. I don’t see the value in adding more complexity to api keys here.
