### ISSUE TITLE
Is there any way to implement Single Sign In using Appwrite?

### ISSUE THREAD

**Issue by Achraf112Ben** [appwrite/appwrite#8034]
### 🔖 Enhancement description

Hi guys, I have a question please.

Can SSI (Single Sign In) be implemented one way or an other using Appwrite?

What I'm basically trying to implement is a kind of a supper app just like Google or Meta which have a lot off apps and services under it's wing for various purposes.

I'd like a user to be able to Sign In only one time on the mother app and be automatically signed in on all the sub-apps as a result. Exactly like it is for when you sign in once on google and you can use that single sign in on all google products: Youtube, Search, Maps, etc. 

One thing to note is some of these sub-apps would have their independent domain names while others would only have a subdomain of the mother app.

So far, the only straight forward way I've thought of to implement this usecase using Appwrite is to put all the sub-apps under the same project/database. But I'm afraid that this would hinder greatly the performance of Appwrite and would make the projects messy and difficult to maintain.

Thanks in advance for your advices  🙏

### 🎤 Pitch

This would help a lot of people have the same usecase as to implement an SSI unsing appwrite

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
To do SSO (single sign on) like you're describing typically requires having some sort of auth provider, but Appwrite doesn't act as an auth provider. 

The best thing to do is probably to use an auth provider that supports OIDC. Then, you can make a project for each app and enable the OAuth2 OIDC provider so that people can log in through the auth provider. The idea is they should already have a session with the provider so they won't need to authenticate again. Instead, they just need to authorize the new project to have access.
