### ISSUE TITLE
🐛 Bug Report: Appwrite Cloud authenticating is broken

### ISSUE THREAD

**Issue by isakjensen** [appwrite/appwrite#8318]
### 👟 Reproduction steps

Running this code

```javascript
let res = await appwrite.account.createEmailPasswordSession(username, password);
```

Then visiting a link of a file uploaded to a Bucket returns "The requested file could not be found."

### 👍 Expected behavior

I thought I could view the image since I added the Read permission on the "All users" option.

### 👎 Actual Behavior

When visiting an image that I should have access to because I selected "Read" on "All users" on a file in my Bucket. But instead it returns

"The requested file could not be found."

The file exists, because when I add "Read" on the option "Any" (no permission needed for anyone), the image is accessible, but its when I set permissions that the image wont be accessible. So authenticating isn't working because my browser isn't able to visit images the user should have permission to.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Sveltekit

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@isakjensen, thanks for raising this issue! 🙏🏼 

Perhaps your session isn't persisting. Are you able to call `account.get()` after `account.createEmailPasswordSession()`? If that throws an error, it confirms the session is not persisting. 

This could be because of your tech stack. If you're using the web SDK (`appwrite` NPM package), the session is persisted using cookies or local storage as a fallback, but these aren't available server-side. For server-side auth, please refer to https://appwrite.io/docs/products/auth/server-side-rendering.
