### ISSUE TITLE
🐛 Bug Report: Issue with Custom SMTP Configuration With SSL on Appwrite Cloud

### ISSUE THREAD

**Issue by akaco** [appwrite/appwrite#8438]
### 👟 Reproduction steps

Unable to save the custom SMTP with SSL settings. Each time I attempt to configure and save the details,
Here are the steps I have taken:

Navigated to the SMTP configuration section under the Pro Plan settings.
Entered all required SMTP details, including server address, port,secure protocol, username, and password.
Clicked on the 'Save' button to store the configuration.
However, upon revisiting the SMTP configuration page, I noticed that the details are not saved.

### 👍 Expected behavior

SSL SMTP port 465 is not accepted and saved.
TLS port 587 is accepted and saved but email sending fails.

### 👎 Actual Behavior

<img width="480" alt="Screenshot 2024-07-24 at 3 08 18 PM" src="https://github.com/user-attachments/assets/2a7fcdd8-ca40-4408-abbc-bc7258e2a162">
<img width="857" alt="Screenshot 2024-07-24 at 3 11 12 PM" src="https://github.com/user-attachments/assets/43e40340-4642-4c75-87bb-dac0aa3a42bc">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@akaco, thanks for raising this issue! 🙏🏼 We had [this patch](https://github.com/appwrite/appwrite/pull/6966) for mails and [this patch](https://github.com/appwrite/appwrite/pull/7915) for messaging, but looks like we need one for the appwrite (API) container as well.

**Comment by y824165978** [comment]
I found the error in console code.

<img width="835" alt="截屏2024-08-10 09 36 59" src="https://github.com/user-attachments/assets/d9de4921-bbad-431c-81ff-080dfc9a519a">

Then I tried to fix it, everything is OK.

<img width="794" alt="截屏2024-08-10 09 57 47" src="https://github.com/user-attachments/assets/a29977b6-434f-4af9-88bb-06841c041b8e">

Before I found this bug, I refer to this [document](https://appwrite.io/docs/products/messaging/smtp) to set up smtp . And Testing is OK. So I try to verification email on [Email and password login](https://appwrite.io/docs/products/auth/email-password#verification) Journey. But nothing works. Until I found [this](https://appwrite.io/docs/advanced/platform/message-templates).

Since I don't know the product requirements, which setting has higher priority, the project or the console, or are the two settings used in completely independent scenarios?
