### ISSUE TITLE
🐛 Bug Report: Query.orderAsc on a string value, when the value is not a string (double or integer)

### ISSUE THREAD

**Issue by ZachHandley** [appwrite/appwrite#8480]
### 👟 Reproduction steps

When I `Query.orderAsc("someStringAttribute")` and the values are a string, but they are integers or floats as a string, it mostly works, but it seems to take the first value or something? E.g. 
![image](https://github.com/user-attachments/assets/8a2ad83a-26e6-4c8c-aa2d-6496c840200c)

### 👍 Expected behavior

Give them in order, if possible, maybe a parsing system or an optional second parameter to give the type?

### 👎 Actual Behavior

Gives them in order based on the first digit, it would seem

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ZachHandley, thanks for creating this issue! 🙏 This is the expected behavior as strings are ordered lexicographically so:

* "a" is less than "b"
* "aa" is less than "ab"
* "0" is less "1"
* "00" is less than "01"

One way to deal with this is to pad the strings so you have:

* 00
* 01
* 10
* 11
* 02

Then, when they're ordered, they'll be ordered like you want. 

Another option is to store them as numbers instead of strings.

Besides that, there's also this request for "natural sorting": https://github.com/appwrite/appwrite/issues/7203

**Comment by ZachHandley** [comment]
interesting, okay, so adding my vote over there is the best way? I understand the sort order, I do think the "natural sorting" order would be more user intuitive, but gotcha! I'll pad my numbers for now, thank you!
