### ISSUE TITLE
🚀 Enhancement: Messaging and topics, allow real pubsub

### ISSUE THREAD

**Issue by yairyairyair** [appwrite/appwrite#8610]
### 🔖 Enhancement description

I want the messaging and topics part to also allow real pubsub and not just email sms and push.

### 🎤 Pitch

For example i want 1 function to push a message of JSON to a topic in appwrite, and another function listens to that topic and reads it and runs. therefore its similar to a real pubsub system.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@yairyairyair, thanks for raising this issue! 🙏🏼 

> push a message of JSON to a topic in appwrite, and another function listens to that topic and reads it and runs

The behavior you're describing sounds like it can be achieved with functions triggered by [events](https://appwrite.io/docs/products/functions/execute#events). So you can:

1. Create a collection as your "topic"
2. Create a function that listens for documents created in the collection
3. Create a document

The function should trigger since it's listening for the document create event.

Would that work for your use case?
