### ISSUE TITLE
🐛 Bug Report: How to get the userID for custom OAuth login?

### ISSUE THREAD

**Issue by LUK3D** [appwrite/appwrite#8711]
### 👟 Reproduction steps

I'm using flutter with `google_sign_in` package to login my users and it returns user info such as email, id, etc. I create an appwrite function to creates a new token and then I can use it to create a new session. The problem is `users.createToken` function requires a user ID and there is no way to get the userId without signing in first.
What is i the correct process/execution flow to sign in users when we only  have the users email and a custom token?
And also, how can we check if the user exists or not so we can create the account?

### 👍 Expected behavior

Be able to create a session from custom OAuth provider

### 👎 Actual Behavior

userID is not found
`{"error":"User with the requested ID could not be found."}`

### 🎲 Appwrite version

Appwrite version 1.5.11

### 💻 Operating system

Linux

### 🧱 Your Environment

Self hosted appwrite on Hetzner

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@LUK3D, thanks for creating this issue! 🙏🏼 

You should probably check if the user exists by users [`users.list()`](https://appwrite.io/docs/references/cloud/server-nodejs/users#list) and using a [`Query`](https://appwrite.io/docs/products/databases/queries) to filter on email.

If the user does not exist, you'll need to [create](https://appwrite.io/docs/references/cloud/server-nodejs/users#create) the user.

FYI, the best place to get help is our [Discord](https://appwrite.io/discord) rather than creating an issue on GitHub.

**Comment by LUK3D** [comment]
> @LUK3D, thanks for creating this issue! 🙏🏼
> 
> You should probably check if the user exists by users [`users.list()`](https://appwrite.io/docs/references/cloud/server-nodejs/users#list) and using a [`Query`](https://appwrite.io/docs/products/databases/queries) to filter on email.
> 
> If the user does not exist, you'll need to [create](https://appwrite.io/docs/references/cloud/server-nodejs/users#create) the user.
> 
> FYI, the best place to get help is our [Discord](https://appwrite.io/discord) rather than creating an issue on GitHub.

Thanks for the suggestions!
