### ISSUE TITLE
🐛 Bug Report: website is not opening 

### ISSUE THREAD

**Issue by salsabeel10** [appwrite/appwrite#8818]
### 👟 Reproduction steps

Appwrite.io website is not opening 

### 👍 Expected behavior

It should work perfectly 

### 👎 Actual Behavior

![Image](https://github.com/user-attachments/assets/73aba943-b2d7-4fcd-a3a5-f749496ee2fc)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Latest 

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by tessamero** [comment]
Hello,

Thank you for reporting this. We are currently investigating a cloud issue. You can check the status in ⁠the #cloud-beta channel within our Discord server. It should be resolved soon as we found the root cause.

You can also sign up for updates and see the current status here: [https://status.appwrite.online/incident/446920](url)
