### ISSUE TITLE
Appwrite shut down

### ISSUE THREAD

**Issue by ssaintx** [appwrite/appwrite#8819]
Appwrite db's are shut down, it's all because of new backup feature!

**Comment by tessamero** [comment]
Hello,

Thank you for reporting this. We are currently investigating a cloud issue. You can check the status in ⁠the #cloud-beta channel within our Discord server. It should be resolved soon as we found the root cause.

You can also sign up for updates and see the current status here: [https://status.appwrite.online/incident/446920](url)
