### ISSUE TITLE
🐛 Bug Report: Appwrite.io Shutdown

### ISSUE THREAD

**Issue by mrinal-mann** [appwrite/appwrite#8820]
### 👟 Reproduction steps

When i open the appwrite.io its not opening

### 👍 Expected behavior

It should open 

### 👎 Actual Behavior

![Image](https://github.com/user-attachments/assets/041bff87-018b-497f-89ec-42cdcfe69ea7)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by tessamero** [comment]
Hello,

Thank you for reporting this. We are currently investigating a cloud issue. You can check the status in ⁠the #cloud-beta channel within our Discord server. It should be resolved soon as we found the root cause.

You can also sign up for updates and see the current status here: [https://status.appwrite.online/incident/446920](url)
