### ISSUE TITLE
Create projects using the CLI

### ISSUE THREAD

**Issue by saibotma** [appwrite/appwrite#925]
## 🚀 Feature

It would be great if we could create projects using the CLI.

## Pitch

This way we could create Appwrite projects from our CI that will be used for developing features.
Every feature would get its own Appwrite instance or project which can be deleted once the feature is implemented.

**Comment by eldadfux** [comment]
@saibotma I have added this to our backlog. Not sure how to implement this because a project would usually require both a user and a related team to be created.

@TorstenDittmann @kodumbeats any ideas about the flow for this issue? without the project API exposed this will be very hard because the next would also include a way to generate the API key.

This can all be done using the regular HTTP REST API when passing the `X-Appwrite-Project` with the value `console` but this is not very intuitive, documented or user friendly.

**Comment by TorstenDittmann** [comment]
> @saibotma I have added this to our backlog. Not sure how to implement this because a project would usually require both a user and a related team to be created.
> 
> @TorstenDittmann @kodumbeats any ideas about the flow for this issue? without the project API exposed this will be very hard because the next step would also include a way to generate the API key.
> 
> This can all be done using the regular HTTP REST API when passing the `X-Appwrite-Project` with the value `console` but this is not very intuitive, documented or user friendly.

We could introduce something like API Keys for Console Accounts 🤔  That would work on the scope of the user like a JWT 🤔

**Comment by alexweininger** [comment]
+1 for being able to create/manage projects via API.

It was discussed on Discord that this functionality would create a more wholistic UX within the [Appwrite VS Code extension](https://github.com/streamlux/vscode-appwrite).

**Comment by punitdiwan** [comment]
+1 for being able to create/manage projects via API and console
