### ISSUE TITLE
Database: Collection names should be IDs

### ISSUE THREAD

**Issue by arnu515** [appwrite/appwrite#984]
## 🚀 Feature
In the database, the collection name should be its id, instead of giving a separate ID for it. This is how it is in Firebase

## Have you spent some time to check if this issue has been raised before?
Yes

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?
Yes

## Pitch
This feature would be a life saver, because when I move from dev environment to production, the collection ids change, which makes it really annoying to change environment variables

**Comment by thegamingninja** [comment]
Yeah, I'd almost consider this is an essential feature. Though I think instead of having the name be the id, the id should be modifiable and is autogenerated by default. That way it is consistent with the rest of the database, having a label/name and a key/id, and doesn't cause any breaking changes.

**Comment by TorstenDittmann** [comment]
What would make sense to me is like an alias for the collection, that can potentially be modified afterwards - even when already referenced since in the endthe real id is the key.

But that would come at a cost, since in the internals the collection ID is an index in MariaDB.

We are planning a refactor on our Database Internals right now and this might be a good suggestion here: https://github.com/appwrite/rfc/pull/21

**Comment by arnu515** [comment]
> Though I think instead of having the name be the id, the id should be
modifiable and is autogenerated by default

That's an amazing idea

**Comment by jackv24** [comment]
+1 it'd be really helpful to be able to modify the ID of collections ***and*** documents

**Comment by eldadfux** [comment]
Update 27-05-21: We are actively testing custom IDs for both collections and documents 😍

**Comment by eldadfux** [comment]
Update 06-08-21: We have got the custom IDs PR merged. This feature is expected to be released as part of Appwrit 0.10.0.
https://github.com/appwrite/appwrite/pull/1350

**Comment by eldadfux** [comment]
This feature is currently planned for 0.11

**Comment by eldadfux** [comment]
Custom IDs are ready and will be released as part of Appwrite 0.12.

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
